### PR TITLE
Feature: zookeeper outside of docker

### PR DESCRIPTION
**Pull request by avnik**
Use zookeeper from mesosphere packages, and zookeepercli from their own rpm

Looks workign for me,  timeouts during acl set happens, but they now really timeouts, so second run of playbook finished ok

### CODE REVIEW

**Comment by ryane** [comment]
I am getting a consistent failure on a vagrant install:

```
=> default: TASK: [mesos | create zookeeper acl] ******************************************
==> default: failed: [default] => {"changed": true, "cmd": ["zookeepercli", "-servers", "zookeeper.service.consul:2181", "-auth_usr=super", "-auth_pwd=/jjlzjvTvHevgBGPv60yM83tQyi7Co7FMqAQ+51cLRmC", "-force", "-c", "setacl", "/mesos", "world:anyone:r,digest:mesos:b9DPNWn5Mak+Cv9bpYGEkomxJHs=:cdraw"], "delta": "0:00:00.151983", "end": "2015-11-30 21:34:02.433089", "rc": 1, "start": "2015-11-30 21:34:02.281106", "warnings": []}
==> default: stderr: 2015/11/30 21:34:02 Failed to connect to zookeeper.service.consul:2181: dial tcp: lookup zookeeper.service.consul: No address associated with hostname
==> default: 2015-11-30 21:34:02 FATAL zk: could not connect to a server
==> default:
==> default: FATAL: all hosts have already failed -- aborting
```

**Comment by ryane** [comment]
also failing on openstack:

```
NOTIFIED: [zookeeper | restart zookeeper] *************************************
changed: [resching-lon1-test-control-02]
changed: [resching-lon1-test-control-01]
changed: [resching-lon1-test-control-03]

NOTIFIED: [zookeeper | wait for zookeeper to listen] **************************
failed: [resching-lon1-test-control-01] => {"changed": true, "cmd": ["/usr/local/bin/zookeeper-wait-for-listen.sh", "resching-lon1-test-control-01"], "delta": "0:01:00.353834", "end": "2015-11-30 22:40:57.612668", "rc": 1, "start": "2015-11-30 22:39:57.258834", "warnings": []}
failed: [resching-lon1-test-control-03] => {"changed": true, "cmd": ["/usr/local/bin/zookeeper-wait-for-listen.sh", "resching-lon1-test-control-03"], "delta": "0:01:00.413658", "end": "2015-11-30 22:40:57.665036", "rc": 1, "start": "2015-11-30 22:39:57.251378", "warnings": []}
failed: [resching-lon1-test-control-02] => {"changed": true, "cmd": ["/usr/local/bin/zookeeper-wait-for-listen.sh", "resching-lon1-test-control-02"], "delta": "0:01:00.421904", "end": "2015-11-30 22:40:57.677303", "rc": 1, "start": "2015-11-30 22:39:57.255399", "warnings": []}

FATAL: all hosts have already failed -- aborting
```

**Comment by ryane** [comment]
Disregard the last comment about the openstack failure. I was testing with the wrong branch as I was originally using the wrong jump box. It does appear to be working well on openstack.

**Comment by benschumacher** [comment]
I obviously don't know all the context from this PR, but I'm somewhat concerned about this change. My initial impressions is that moving outside of Docker as our packaging solution makes our deployment somewhat more inflexible. How would this effect long term maintenance / upgradability?

**Comment by eirslett** [comment]
@benschumacher The main concern with running ZooKeeper inside Docker is that it decreases availability. (If Docker is upgraded, or fails for some reason, then ZooKeeper fails too).
It's desirable to have ZooKeeper (and Mesos) running even if Docker doesn't work properly.
So it's more of a compromise between flexibility and availability.

**Comment by stevendborrelli** [comment]
@benschumacher it's a tradeoff. From running mantl clusters for a while now we are finding that there are advantages for critical system-level services to run outside of docker. As @eirslett noted, docker processes tend to be less stable than processes running on the system. 

There's a network bridge, docker has its own storage manger that can lock up or have performance issues.

I think do you raise a good point in that docker is a very good packaging format. The first versions of mantl were just systemd + docker. We're still very interested in that model, and I hope that something like https://github.com/coreos/rkt can gain traction.

**Comment by ryane** [comment]
this seems to be working well. successful on vagrant, aws, gce, do, and openstack.

**Comment by prudhvitella** [comment]
In my OpenStack environment, I got the following error:
```
failed: [ci-control-03] => {"changed": true, "cmd": ["zookeepercli", "-servers", "zookeeper.service.consul:2181", "-auth_usr=super", "-auth_pwd=fXTBpO3Sv6Ti7Wu49hzRMuDSZDXWWPRzWxaU6ohb1cyB", "-force", "-c", "setacl", "/mesos", "world:anyone:r,digest:mesos:F4/N0cGM8mPx4GkVwJ4Fr7bFTgk=:cdraw"], "delta": "0:00:00.031627", "end": "2015-12-03 03:48:08.031037", "rc": 1, "start": "2015-12-03 03:48:07.999410", "warnings": []}
stderr: 2015-12-03 03:48:08 FATAL zk: could not connect to a server

FATAL: all hosts have already failed -- aborting
```

**Pull request merged**
