### PR TITLE
Fix resolv.conf overwriting by DHCP stuff

### PR DESCRIPTION
**Pull request by avnik**

### CODE REVIEW

**Comment by avnik** [comment]
@stevendborrelli  @BrianHicks  would be nice, if this commit hits 0.5.1

**Comment by BrianHicks** [comment]
so, what exactly is this doing?

**Comment by eirslett** [comment]
(and why is it doing it?)

**Comment by avnik** [comment]
NetworkManager read this "old-style" setting, and it take priority over "dns=none" in own NetworkManager.conf
And this works.

**Comment by avnik** [comment]
So this change  find all ifcfg-ethX scripts, and change PEERDNS to NO

**Comment by BrianHicks** [comment]
I guess I should have been clearer: I can see what this is doing, but *why* is it doing it? (thanks @eirslett)

Specifically, does it need to be documented? How can I test it?

**Comment by avnik** [comment]
At least Cisco Openstack images have PEERDNS=yes,  and it follow overwrite /etc/resolv.conf after reboot.

Suggested check sequence: deploy on Openstack, check
`ansible all -u cloud-user -i plugins/inventory/terraform.py -b -m shell -a "cat /etc/resolv.conf"` for current state.
Reboot, and check again:  file is overwritten by NetworkManager.
Then deploy fixed version,  check-reboot-check.
File not overwritten any more.

**Comment by TanyaCouture** [comment]
1. Deployed to Openstack
2. Installed addons/glusterfs
3. ansible all -u cloud-user -i plugins/inventory/terraform.py -b -m shell -a "cat /etc/resolv.conf": success  
    on all nodes
4. Copied file to /mnt/container-volumes"
5. listed container volumes: success on the 3 control nodes and the 3 worker nodes. failed on the 2 edge nodes. 
6. rebooted
7. listed container-volumes: success on the 3 control nodes and the 3 worker nodes. failed on the 2 edge 
    nodes.

**Comment by ryane** [comment]
the failures on edge nodes are expected since we only mount gluster volumes on worker nodes

**Comment by avnik** [comment]
@TanyaCouture  failure on edge is ok.

Can you please test it on one other cloudprovider, before we can merge it?

**Comment by ohal** [comment]
test this please

**Comment by ryane** [comment]
successful test on GCE. @avnik is this ready to merge or were you planning on incorporating something from #952?

**Comment by avnik** [comment]
On Wed, Jan 06, 2016 at 03:17:46PM -0800, Ryan Eschinger wrote:

> successful test on GCE. @avnik is this ready to merge or were you planning on incorporating something from #952?
> 

As I discuss with @larry-svds, I will incorporate some of his changes, but later by separate PR.
This one is OK for merge.

**Pull request merged**
