### PR TITLE
mesos 0.25

### LINKED ISSUE #988: mesos no longer logging to disk
After the switch to the new packaging, mesos is no longer logging to disk. This means that logs are no longer available in the mesos UI and the mesos-specific logstash rules are not being applied.

### LINKED ISSUE #995: Revert to Mesos 0.25
Unfortunately, Mesos 0.26 breaks the Elasticsearch framework (which is being used in production by some Mantl users). 

https://github.com/mesos/elasticsearch/issues/457

We'll need to fix our Mesos install to 0.25 until the issues are resolved.

### PR DESCRIPTION
**Pull request by ryane**
fixes #995 
fixes #988

### CODE REVIEW

**Comment by ryane** [comment]
@sehqlr @TanyaCouture this is ready to test.

**Comment by stevendborrelli** [comment]
Can we merge this?

**Comment by TanyaCouture** [comment]
Deployed successfully with OS:
    -consul is all green, passing
    -mesos not present in /var/log
    -Mesos UI shows version as 0.25.0
        From the Mesos UI:
           Worker node 3 shows failed state

                Active Tasks
                ID	Name	State	Started	Host	
                mantl-api.943941ef-be11-11e5-b7f4-ae40b58ecd56	manta-api	RUNNING  14 minutes          
                       ago	
               mi-worker-001.node.consul	Sandbox
               mesos-consul.7f1e93fc-be11-11e5-b7f4-ae40b58ecd56	mesos-consul	RUNNING	14 
                      minutes ago	
               mi-worker-001.node.consul	Sandbox

               Completed Tasks
 
                ID	Name	State	Started	Stopped	Host	
                mantl-api.8e3d466e-be11-11e5-b7f4-ae40b58ecd56	mantl-api	FAILED	14 minutes ago	
                    14 minutes ago	
               mi-worker-003.node.consul	Sandbox
               mantl-api.821bf57d-be11-11e5-b7f4-ae40b58ecd56	mantl-api	FAILED	14 minutes ago	
                        14 minutes ago	
               mi-worker-003.node.consul	Sandbox 


Deployed successfully to DO, but
mesos was not present in /var/log.

**Comment by ryane** [comment]
lgtm. the failed mesos tasks were due to mesos not being registered when they started up. by the time the cluster provisioned fully, that task started and was running correctly.

also, had a successful deployment on GCE. ready to merge.

**Pull request merged**
