### PR TITLE
Document Terraform changes

### PR DESCRIPTION
**Pull request by BrianHicks**
- document Terraform changes in the getting started guide
- add a new GCE section for Terraform
- update the existing OpenStack section for Terraform
- change the roadmap
- fix formatting everywhere in the docs
- add some awesome images
- probably the start of the singularity or something, I don't know.

### CODE REVIEW

**Comment by BrianHicks** [comment]
anyway, if someone like @keithchambers or @stevendborrelli could give these changes a quick look, I'd appreciate it.

**Comment by siddharthist** [comment]
Although I haven't been able to test on Openstack or GCE entirely yet, here's some preliminary feedback: 
 * I couldn't use Service Account in GCE, as I am not project owner. This might be mentioned. 
 * I didn't understand the distinction between the two region fields. 
 * "Customizing your deployment" should be moved up.
 * This command should include security.yml: `ansible-playbook -i plugins/inventory/terraform.py terraform.yml`

**Comment by siddharthist** [comment]
After getting everything provisioned on Openstack, I'd say the documentation looks good!

**Comment by stevendborrelli** [comment]
@siddharthist I'll merge this, can you submit a pull for the documentation changes you suggested?

**Comment by BrianHicks** [comment]
@stevendborrelli

- service account: 8ad7fc8
- moving link up: a2dd530
- region fields: 86c77e1 
- security.yml in command: 3b061d0

**Pull request merged**
