### PR TITLE
Feature/granular security

### PR DESCRIPTION
**Pull request by ChrisAubuchon**
This adds several options to `security-setup` to disable/enable specific security options.

Command options added
* --disable-consul-auth
* --disable-consul-ssl
* --disable-consul-acl
* --disable-mesos-ssl
* --disable-mesos-auth
* --disable-mesos-framework-auth
* --disable-mesos-follower-auth
* --disable-mesos-iptables
* --disable-marathon-ssl
* --disable-marathon-auth
* --disable-marathon-iptables

Each option has an accompanying `--enable` option.

### CODE REVIEW

**Comment by keithchambers** [comment]
I recommend we clean up our `--help`.  Specifically I recommend we move to having `true|false` switches like Docker.

Generally speaking I really like the Docker help output.  Let's just copy their formatting all they down to how they do indenting.

```
$ ./security-setup --help
usage: set up authentication and security for various components

optional arguments:
  -h, --help            show this help message and exit
  --no-verify-certificates
                        skip verifying certificates
  --change-admin-password
                        change admin password
  --cert-country CERT_COUNTRY
  --cert-state CERT_STATE
  --cert-locality CERT_LOCALITY
  --cert-organization CERT_ORGANIZATION
  --cert-unit CERT_UNIT
  --cert-email CERT_EMAIL
  --consul-location CONSUL_LOCATION
  --nginx-location NGINX_LOCATION
  --disable-consul-auth
                        disable consul auth
  --enable-consul-auth  enable consul auth
  --disable-consul-ssl  disable consul ssl
  --enable-consul-ssl   enable consul ssl
  --disable-consul-acl  disable consul ACLs
  --enable-consul-acl   enable consul ACLs
  --disable-mesos-ssl   disable mesos ssl
  --enable-mesos-ssl    enable mesos ssl
  --disable-mesos-auth  disable mesos auth
  --enable-mesos-auth   enable mesos auth
  --disable-mesos-framework-auth
                        disable mesos framework auth
  --enable-mesos-framework-auth
                        enable mesos framework auth
  --disable-mesos-follower-auth
                        disable mesos follower auth
  --enable-mesos-follower-auth
                        enable mesos follower auth
  --disable-mesos-iptables
                        disable mesos iptables
  --enable-mesos-iptables
                        enable mesos iptables
  --disable-marathon-ssl
                        disable marathon ssl
  --enable-marathon-ssl
                        enable marathon ssl
  --disable-marathon-auth
                        disable marathon auth
  --enable-marathon-auth
                        enable marathon auth
  --disable-marathon-iptables
                        disable marathon iptables
  --enable-marathon-iptables
                        enable marathon iptables
```

```
[vagrant@localhost ~]$ docker
Usage: docker [OPTIONS] COMMAND [arg...]

A self-sufficient runtime for linux containers.

Options:
  --add-registry=[]                    Registry to query before a public one
  --api-cors-header=                   Set CORS headers in the remote API
  -b, --bridge=                        Attach containers to a network bridge
  --bip=                               Specify network bridge IP
  --block-registry=[]                  Don't contact given registry
  -D, --debug=false                    Enable debug mode
  -d, --daemon=false                   Enable daemon mode
  --default-ulimit=[]                  Set default ulimits for containers
  --dns=[]                             DNS server to use
  --dns-search=[]                      DNS search domains to use
  -e, --exec-driver=native             Exec driver to use
  --fixed-cidr=                        IPv4 subnet for fixed IPs
  --fixed-cidr-v6=                     IPv6 subnet for fixed IPs
  -G, --group=docker                   Group for the unix socket
  -g, --graph=/var/lib/docker          Root of the Docker runtime
  -H, --host=[]                        Daemon socket(s) to connect to
  -h, --help=false                     Print usage
  --icc=true                           Enable inter-container communication
  --insecure-registry=[]               Enable insecure registry communication
  --ip=0.0.0.0                         Default IP when binding container ports
  --ip-forward=true                    Enable net.ipv4.ip_forward
  --ip-masq=true                       Enable IP masquerading
  --iptables=true                      Enable addition of iptables rules
  --ipv6=false                         Enable IPv6 networking
  -l, --log-level=info                 Set the logging level
  --label=[]                           Set key=value labels to the daemon
  --mtu=0                              Set the containers network MTU
  -p, --pidfile=/var/run/docker.pid    Path to use for daemon PID file
  --registry-mirror=[]                 Preferred Docker registry mirror
  -s, --storage-driver=                Storage driver to use
  --selinux-enabled=false              Enable selinux support
  --storage-opt=[]                     Set storage driver options
  --tls=false                          Use TLS; implied by --tlsverify
  --tlscacert=~/.docker/ca.pem         Trust certs signed only by this CA
  --tlscert=~/.docker/cert.pem         Path to TLS certificate file
  --tlskey=~/.docker/key.pem           Path to TLS key file
  --tlsverify=false                    Use TLS and verify the remote
  -v, --version=false                  Print version information and quit

Commands:
    attach    Attach to a running container
    build     Build an image from a Dockerfile
    commit    Create a new image from a container's changes
    cp        Copy files/folders from a container's filesystem to the host path
    create    Create a new container
    diff      Inspect changes on a container's filesystem
    events    Get real time events from the server
    exec      Run a command in a running container
    export    Stream the contents of a container as a tar archive
    history   Show the history of an image
    images    List images
    import    Create a new filesystem image from the contents of a tarball
    info      Display system-wide information
    inspect   Return low-level information on a container or image
    kill      Kill a running container
    load      Load an image from a tar archive
    login     Register or log in to a Docker registry server
    logout    Log out from a Docker registry server
    logs      Fetch the logs of a container
    port      Lookup the public-facing port that is NAT-ed to PRIVATE_PORT
    pause     Pause all processes within a container
    ps        List containers
    pull      Pull an image or a repository from a Docker registry server
    push      Push an image or a repository to a Docker registry server
    rename    Rename an existing container
    restart   Restart a running container
    rm        Remove one or more containers
    rmi       Remove one or more images
    run       Run a command in a new container
    save      Save an image to a tar archive
    search    Search for an image on the Docker Hub
    start     Start a stopped container
    stats     Display a stream of a containers' resource usage statistics
    stop      Stop a running container
    tag       Tag an image into a repository
    top       Lookup the running processes of a container
    unpause   Unpause a paused container
    version   Show the Docker version information
    wait      Block until a container stops, then print its exit code

Run 'docker COMMAND --help' for more information on a command.
```

**Comment by keithchambers** [comment]
I think we should have some "wrapper" `true|false` options like:
* `--disable` which disables security for everything
* `--enable` which disables security for everything
* `--consul=false` which enables/disabled all Consul security
* `--mesos=false` which enables/disabled all Mesos security
* `--marathon=false` which enables/disabled all Marathon security
* `--iptables=false` which enables/disables iptables for all

**Comment by keithchambers** [comment]
While we are refactoring command arguments let's make this changes also:
* `--no-verify-certificates` becomes `--certificates=false`
* `--change-admin-password` becomes `--password --user=admin <value>`

**Comment by BrianHicks** [comment]
I agree that it could be clearer. However, I think changing the format would be a waste of time for something so cosmetic. Could we instead:

 - change en/disable commands to a single boolean flag? So `--enable-mesos-framework-auth` becomes `--mesos-framework-auth={1,0,true,false}`
 - use Python's built-in [default including formatter](https://docs.python.org/2/library/argparse.html?highlight=argparse#argparse.ArgumentDefaultsHelpFormatter):

    ```
    usage: PROG [-h] [--foo FOO] [bar [bar ...]]

    positional arguments:
     bar         BAR! (default: [1, 2, 3])

    optional arguments:
     -h, --help  show this help message and exit
     --foo FOO   FOO! (default: 42)
    ```

- have only `--disable` as a coarse-grained flag. `--enable` is implied.

**Comment by keithchambers** [comment]
@BrianHicks I'm OK with these changes you are proposing.

One point I do want to make is that things that make our system easier for our users are *never* a waste of time.

**Comment by BrianHicks** [comment]
@keithchambers sounds good, we'll go ahead and implement it that way then. I agree that it's not a waste of time, I could have phrased it better: we can get a few quick UX wins out of the help formatter but emulating the go formatting precisely invokes the law of diminishing returns pretty quickly.

**Comment by keithchambers** [comment]
So let's go ahead and merge this now and then we will open a new issue for the coarse gain options and argument refactoring.

**Pull request merged**
