### PR TITLE
aws bugfix

### PR DESCRIPTION
**Pull request by ack**
role should be edge, pull up and default route53 vars

### CODE REVIEW

**Comment by TanyaCouture** [comment]
Should the route53 variables and route53 module be commented out by default? Also, the route53.rst refers to the aws-elb module and ELB.

**Comment by anners** [comment]
@TanyaCouture imo I would leave in uncommented and let people comment it out if they don't want to use it, but I can see an argument being made the other way since DNS/Route53 is not required to make mantl work. The terraform route53 example also references the elbs, DNS is getting created for the edge/traefik elb and and the UI elb.

**Comment by TanyaCouture** [comment]
Commented out route53 module and variables dns_subdomain, dns_domain, and dns_zone_id and  successful installed with aws. All nodes healthy.

**Comment by ryane** [comment]
good catch, thanks @ack

**Pull request merged**
