### PR TITLE
Localhost can't resolve hostnames of provisioned machines without... (fixes #134)

### LINKED ISSUE #134: Localhost can't resolve hostnames of provisioned machines without external DNS
I have provisioned a cluster following the getting started instructions.  The problem is that my local machine where Ansible is installed is not able to resolve hostnames of the provisioned machines ("host-01", etc.)

Even when I moved Ansible to a new machine in Openstack cluster itself, that machine was not able to resolve them as well.  That was expected, I just wanted to make sure there is no "magic" here.

Provisioned machines are able to reach each other because the hostnames have been added to their /etc/hosts files.

My solution was to add them in my local /etc/hosts as well.  To do that I have added the following code into provision-hosts.yml:

- hosts: localhost
  gather_facts: no
  connection: local
  sudo: yes
  tasks:
    - name: update /etc/hosts file
      local_action: lineinfile
        dest=/etc/hosts
        regexp=".*{{ item }}$"
        line="{{ hostvars[item].ansible_ssh_host }} {{ item }}"
        state=present
      when: hostvars[item].ansible_ssh_host is defined
      with_items: groups['all']
      always_run: yes
      tags: host

Please consider applying a fix like that (or you can create a separate playbook not to mix up with existing provision-hosts.yml) or suggest a better solution.

Thanks!

### PR DESCRIPTION
**Pull request by OleksandrBerchenko**
Updating both "provision-hosts.yml" and "destroy-hosts.yml" to add/remove appropriate lines to/from "/etc/hosts" on localhost.

[Review on Reviewable](https://reviewable.io/reviews/ciscocloud/microservices-infrastructure/146)

### CODE REVIEW

**Comment by OleksandrBerchenko** [comment]
> We use the dest: /etc/hosts code style vs dest=/etc/hosts. Can you please update the PR with this style?

I'm not sure this style will work in case of "local_action: lineinfile".  The following code:

```
      local_action: lineinfile
        dest: /etc/hosts
        regexp: ".*{{ item }}$"
        state: absent
```
crashes with the following error:

```
ERROR: Syntax Error while loading YAML script, openstack/provision-hosts.yml
Note: The error may actually appear before this position: line 61, column 13

      local_action: lineinfile
        dest: /etc/hosts
```

All examples I found in Internet use "=" for that, even if the rest of the file uses ":".  For example, see https://github.com/zoni/Vagrant-Ansible-example/blob/master/add-vagrant-hostnames-to-etc-hosts.yml

Thanks!

**Comment by keithchambers** [comment]
Try:

```
- hosts: localhost
  gather_facts: no
  sudo: yes
  tasks:
    - name: update /etc/hosts
      local_action:
        module: lineinfile
        dest: "/etc/hosts"
        regexp: ".*{{ item }}$"
        state: absent
      with_items: groups['all']
```

Does that work?

**Comment by OleksandrBerchenko** [comment]
Yes, that works, thanks!

**Comment by keithchambers** [comment]
Awesome!

@stevendborrelli @ChrisAubuchon @BrianHicks -- what are you thoughts on this functionality?  How would (could ?) we maintain this functionality if we switch from Ansible to Terraform?

**Comment by stevendborrelli** [comment]
I think we can pull data from the terraform state file to do something similar.

**Comment by stevendborrelli** [comment]
+1 on the role itself.

This is failing for me. This is because my sudo setup requires a password. If I invoke with ``--ask-sudo-password`` it works fine. I'm wondering if updating /etc/hosts should be part of the main workflow.

```
TASK: [add hosts to local /etc/hosts] ***************************************** 
skipping: [localhost] => (item=localhost)
failed: [localhost -> 127.0.0.1] => (item=host-01) => {"failed": true, "item": "host-01", "parsed": false}
[sudo via ansible, key=gfyfgefuklvumpzjliblsrtowwjijlwb] password: 
```

**Comment by keithchambers** [comment]
@stevendborrelli are you thinking we should break this out in to it's own "helper" playbook?

**Comment by stevendborrelli** [comment]
I think it should be a separate activity to update your local `/etc/hosts` file. Making modifications (as root) to someone's system should be an explicit action. 

Maybe we prompt after the run if any servers were provisioned or deleted: 
```run ansible-playbook -i inventory/xxxx update-hostfile.yml --sudo-askpass to update your local /etc/hosts file```

**Comment by OleksandrBerchenko** [comment]
So, what is a final decision?

I can create a new playbook with that code (or probably two playbooks - one to add records and another to remove them after destroy-hosts.yml) and add a message to provision-hosts.yml/destroy-hosts.yml.

**Comment by stevendborrelli** [comment]
@OleksandrBerchenko +1 on the new playbook and updating provision and destroy to ask to update /etc/hosts.

**Comment by OleksandrBerchenko** [comment]
I run into an issue:
- to update /etc/hosts you need to know IP addresses of the hosts
- to get IP addresses of the hosts you need to gather facts about the hosts
- to gather facts about the hosts you need to know their IPs :)

You know IPs addresses of the hosts only inside provision-hosts.yml (because Openstack returned them to you) and it seems to be the single place where you can update /etc/hosts.

Do I miss anything?

Thanks!

**Comment by OleksandrBerchenko** [comment]
Well, we can obtain hostnames' IPs from OpenStack again (by parsing an output of "nova list" command), but that will be a bit more complicated.

Is there any case when updating a local /etc/hosts automatically during provisioning may do any harm?

What do you think?

Thanks!

**Comment by OleksandrBerchenko** [comment]
So, any thoughts? :)

Thank you!

**Comment by cdmitri** [comment]
From my testing I think we should make it part of the main flow, but also have a naming convention for the hosts so that they don't clash between the DC's. It will be awesome if we could run 1 command and access all the services right away from the place where we ran the command from instead of multiple steps and/or config changes like hostname aliases.

Business case: someone wants to provision a bigdata stack and use machine learning and see spark jobs right away, without having to do admin stuff like managing /etc/hosts file on the local machine :)

Cheers,
D.

**Comment by cdmitri** [comment]
Oleksandr, can't you please see if you can generate a file with all the hostnames during the provisioning so that we can have an option of merging later with the local /etc/hosts file? Let's have that as compromise and move with the pull request asap.

Cheers,
D.

**Comment by OleksandrBerchenko** [comment]
Please review.

Thanks!

**Comment by OleksandrBerchenko** [comment]
Guys, what do you think?

Thanks!

**Comment by stevendborrelli** [comment]
@OleksandrBerchenko testing this today. Sorry for the delay.

**Pull request merged**
