### PR TITLE
Feature/distributive rpm integration

### PR DESCRIPTION
**Pull request by siddharthist**
Integrate all the tests we've written for MI in distributive-rpm. This is not complete coverage, several had to be taken out due to permission errors, and I'm sure we can think of more to add, but this is a great baseline for testing.

### CODE REVIEW

**Comment by ohal** [comment]
@ test this please

**Comment by ohal** [comment]
@ ok to test

**Comment by siddharthist** [comment]
Tested on Vagrant, DO, and now Openstack.

**Comment by siddharthist** [comment]
Tested on AWS and GCE.

**Pull request merged**
