### PR TITLE
Add support for Infoblox DNS Provider

### PR DESCRIPTION
**Pull request by prudhvitella**
This PR adds support for Infoblox DNS provider. This provider is still in the process of being merged to Terraform's master branch. https://github.com/hashicorp/terraform/pull/4006

### CODE REVIEW

**Comment by siddharthist** [comment]
I feel similarly to the dicussion in that issue, i.e. this would be very difficult to maintain considering we don't have any Infoblox infrastructure. We need to find a better way to house this kind of community-supported code without having it as a part of Mantl itself. 

It seems to me that two good options would be to either
 * have a separate mantl-contrib repo for community supported resources, or
 * house this kind of code under addons/, like we did for GlusterFS.

What do you think, @stevendborrelli?

**Comment by stevendborrelli** [comment]
Terraform can use remote modules. So instead of having this in core, we could have community modules external to the project. 

In fact, I'd rather move all the terraform configs to remote so that they can be shared by multiple projects.

```
module "consul" {
    source = "github.com/hashicorp/consul/terraform/aws"
    servers = 3
}
```

**Comment by prudhvitella** [comment]
Remote modules is a good idea. Is the plan place these in a central project or just import from personal space?

**Comment by stevendborrelli** [comment]
There are discussions to move mantl into its own github org (think github.com/mantl/). At that point we could have something like mantl/terraform and mantl/terraform-community

**Comment by siddharthist** [comment]
I'm going to close this because we can't merge it until we have terraform remote modules or a github organization. If we get a clear plan of how to support community terrform modules, let's look into this again!

**Pull request closed without merging**
