### PR TITLE
Fix: replace mesosphere repo with direct links on packages

### PR DESCRIPTION
**Pull request by avnik**
Also contain commit which increase timeouts in yum,

### CODE REVIEW

**Comment by TanyaCouture** [comment]
Successful installation on:
AWS (all green on UI)

**Comment by stevendborrelli** [comment]
@TanyaCouture can you please run `yum -y upgrade` all on each of the nodes?

**Comment by TanyaCouture** [comment]
@stevendborrelli The above was from the current version. Upgrade from a 0.5.1 tag as well?

**Comment by ryane** [comment]
@TanyaCouture this pr is intended to fix #1025. so you just want to make sure you can run 

`sudo yum upgrade -y`

on all nodes successfully, without any conflicts.

**Comment by ryane** [comment]
+1 gce. I am able to run successfully run `yum upgrade` without conflicts.

**Pull request merged**
