### PR TITLE
Add Route53 DNS support

### PR DESCRIPTION
**Pull request by wangqiang8511**
Add route53 dns support. The host name is the same as dnsimple.

### CODE REVIEW

**Comment by eirslett** [comment]
+1 more DNS providers is good!
I think this PR needs some documentation added as well.

**Comment by ryane** [comment]
thanks, this looks great! Would you mind adding some docs as @eirslett suggested? Take a look at #734, #726, and #653 for examples. With AWS, it is also helpful to include the IAM permissions that are required.

**Comment by ryane** [comment]
also, can you double check the creation of the `dns-worker-haproxy` record? It doesn't look like it would include all of the worker ips. You shouldn't need to use `count` and `element` since `records` accepts a list.

**Comment by wangqiang8511** [comment]
Hi, @eirslett I add some docs for route53 dns support.  @ryane  I also fixed the lb haproxy error.

**Comment by ryane** [comment]
thanks @wangqiang8511. this has been merged

**Pull request merged**
