### PR TITLE
Feature/consul healthcheck

### PR DESCRIPTION
**Pull request by steel4ge**
This feature enables health checks for disk/memory/load average in consul.

### CODE REVIEW

**Comment by keithchambers** [comment]
@steel4ge thank you for this! I'll take a look today and provide feedback.

**Comment by keithchambers** [comment]
Thinking out loud here -- I wonder if CPU and Memory checks make sense for the resource nodes.  I can see situations where people want to run them at 100%.  I can see us needing different settings for controller and resource nodes.

What do others think?

**Comment by nmarasoiu** [comment]
A load average threashold could test if in fact processes/tasks are waiting due to overscheduling.
For instance in a linux box, if I see the first number at "w", a number over the number of virtual cores i have in that machine, it typically means that the kernel has a waiting queue of RUNNING tasks (processes)

**Comment by siddharthist** [comment]
I'm testing this now.

**Comment by siddharthist** [comment]
Results:
 * Services are runnning normally 
 * `curl http://[some-ip]:8500/v1/health/state/critical` returns an empty list. Yay!
 * LGTM

**Pull request closed without merging**
