### PR TITLE
Bug in ansible collectd role

### PR DESCRIPTION
**Pull request by steel4ge**
Bug in ansible collectd role which affects master branch deployment.

Ansible output:
```
TASK: [docker | install collectd docker plugin] ***************************** 
failed: [qa3-worker-02] => (item=dockerplugin.py) => {"checksum": "a643733cc27e880197f40925ba045aac59d11788", "failed": true, "item": "dockerplugin.py"}
msg: Destination directory /usr/share/collectd/plugins does not exist

TASK: [docker | configure collectd docker plugin] *************************
failed: [qa3-control-03] => {"checksum": "7d8913212991dd5b5a7ac2dd7ffa96a8b06a19d7", "failed": true}
failed: [qa3-worker-02] => {"checksum": "7d8913212991dd5b5a7ac2dd7ffa96a8b06a19d7", "failed": true}
msg: Destination directory /etc/collectd.d does not exist
msg: Destination directory /etc/collectd.d does not exist
```

### CODE REVIEW

**Comment by siddharthist** [comment]
I'm testing this now.

**Comment by siddharthist** [comment]
This fails for me with this message:
```
TASK: [docker | install collectd docker plugin] ******************************* 
failed: [lbarrett-worker-02] => (item=dockerplugin.py) => {"checksum": "a643733cc27e880197f40925ba045aac59d11788", "failed": true, "item": "dockerplugin.py"}
msg: Destination directory /usr/share/collectd/plugins does not exist
failed: [lbarrett-worker-03] => (item=dockerplugin.py) => {"checksum": "a643733cc27e880197f40925ba045aac59d11788", "failed": true, "item": "dockerplugin.py"}
msg: Destination directory /usr/share/collectd/plugins does not exist
failed: [lbarrett-control-02] => (item=dockerplugin.py) => {"checksum": "a643733cc27e880197f40925ba045aac59d11788", "failed": true, "item": "dockerplugin.py"}
msg: Destination directory /usr/share/collectd/plugins does not exist
failed: [lbarrett-control-03] => (item=dockerplugin.py) => {"checksum": "a643733cc27e880197f40925ba045aac59d11788", "failed": true, "item": "dockerplugin.py"}
msg: Destination directory /usr/share/collectd/plugins does not exist
failed: [lbarrett-control-01] => (item=dockerplugin.py) => {"checksum": "a643733cc27e880197f40925ba045aac59d11788", "failed": true, "item": "dockerplugin.py"}
msg: Destination directory /usr/share/collectd/plugins does not exist
failed: [lbarrett-worker-01] => (item=dockerplugin.py) => {"checksum": "a643733cc27e880197f40925ba045aac59d11788", "failed": true, "item": "dockerplugin.py"}
msg: Destination directory /usr/share/collectd/plugins does not exist
failed: [lbarrett-worker-03] => (item=dockerplugin.db) => {"checksum": "cb9869abf27be8534e73eba215dec6320de8c2ce", "failed": true, "item": "dockerplugin.db"}
msg: Destination directory /usr/share/collectd/plugins does not exist
failed: [lbarrett-worker-02] => (item=dockerplugin.db) => {"checksum": "cb9869abf27be8534e73eba215dec6320de8c2ce", "failed": true, "item": "dockerplugin.db"}
msg: Destination directory /usr/share/collectd/plugins does not exist
failed: [lbarrett-control-02] => (item=dockerplugin.db) => {"checksum": "cb9869abf27be8534e73eba215dec6320de8c2ce", "failed": true, "item": "dockerplugin.db"}
msg: Destination directory /usr/share/collectd/plugins does not exist
failed: [lbarrett-control-03] => (item=dockerplugin.db) => {"checksum": "cb9869abf27be8534e73eba215dec6320de8c2ce", "failed": true, "item": "dockerplugin.db"}
msg: Destination directory /usr/share/collectd/plugins does not exist
failed: [lbarrett-control-01] => (item=dockerplugin.db) => {"checksum": "cb9869abf27be8534e73eba215dec6320de8c2ce", "failed": true, "item": "dockerplugin.db"}
msg: Destination directory /usr/share/collectd/plugins does not exist
failed: [lbarrett-worker-01] => (item=dockerplugin.db) => {"checksum": "cb9869abf27be8534e73eba215dec6320de8c2ce", "failed": true, "item": "dockerplugin.db"}
msg: Destination directory /usr/share/collectd/plugins does not exist

FATAL: all hosts have already failed -- aborting
```

**Comment by siddharthist** [comment]
Looks like the Docker role is running before the collectd role, which actually creates that directory.

**Comment by steel4ge** [comment]
@siddharthist Could you please share which playbook you where using for cluster provisioning?
I've added collectd role before docker in terraform.sample.yml, so it must be played before docker role, hence it should create all folders needed.

**Comment by siddharthist** [comment]
@steel4ge We don't want to rely on the order of the roles to ensure stability. Even if we duplicate our efforts, stability is more important.

**Comment by siddharthist** [comment]
Now I get another error message, this time from Mesos, also related to collectd:
```
NOTIFIED: [mesos | restart collectd] ****************************************** 
failed: [lbarrett-worker-03] => {"failed": true}
msg: Failed to issue method call: Unit collectd.service not loaded.
Failed to issue method call: Unit collectd.service failed to load: No such file or directory.

failed: [lbarrett-worker-02] => {"failed": true}
msg: Failed to issue method call: Unit collectd.service not loaded.
Failed to issue method call: Unit collectd.service failed to load: No such file or directory.

failed: [lbarrett-worker-01] => {"failed": true}
msg: Failed to issue method call: Unit collectd.service not loaded.
Failed to issue method call: Unit collectd.service failed to load: No such file or directory.
```

**Comment by siddharthist** [comment]
This now provisions correctly for me in Vagrant.

**Comment by corebug** [comment]
@siddharthist since collectd is part of core infrastructure, it should be started right after "common role".
It's useless to deploy, say, "docker" role which includes collectd plugin, without the collectd itself.

**Pull request merged**
