### PR TITLE
Move consul DNS domain to a variable

### PR DESCRIPTION
**Pull request by ChrisAubuchon**
* Use `consul_dns_domain` in `inventory/group_vars/all/all.yml` to set the Consul DNS domain

### CODE REVIEW

**Comment by keithchambers** [comment]
I'm thinking the default should be something other than .consul. Maybe .service?

**Comment by ChrisAubuchon** [comment]
If we use .service then we'd wind up with hostnames like consul.service.service and zookeeper.service.service.

**Comment by benschumacher** [comment]
I was just about to say that @ChrisAubuchon. What about .cisco? ;)

**Comment by ChrisAubuchon** [comment]
.micro maybe? It's easy to change so whatever we decide.

**Comment by benschumacher** [comment]
I like .micro. I suppose the question is, is it simple enough that it may become a new gTLD?

**Comment by BrianHicks** [comment]
.local could also make sense.

**Comment by keithchambers** [comment]
@ChrisAubuchon you're right! `.service` is no good then.

@BrianHicks `.local` makes me think localhost or at least local datacenter.

MesosDNS defaults to `.mesos` just like how Consul defaults to `.consul`.

Vote for you favorite from these options:
* `.micro`
* `.registry`
*  `.discovery`
* `.lookup`
* `.dns`
* `.consul` (noop)

**Comment by benschumacher** [comment]
My preference would be either `.micro` or `.consul`.

FYI- `.local` is "reserved" for link-local usage (read: mDNS), and the typical resolution plan should be to check mDNS first, and *maybe* fallback to standard DNS.

**Comment by Y4Rv1K** [comment]
Why not `.server`? So all services will have something like `app.server` =)

**Comment by keithchambers** [comment]
Maybe best to stick with our default of .consul for now.

**Comment by keithchambers** [comment]
I'm going to merge this in.  We can always decide to change the default at a larger date.

Thanks @ChrisAubuchon !

**Pull request merged**
