### PR TITLE
Mesos Packaging

### PR DESCRIPTION
**Pull request by BrianHicks**
In preparation for adding our own Mesos modules, this PR switches to our Mesos packages. They're much simpler.

A second PR will follow soon with support for our own Marathon packages.

### CODE REVIEW

**Comment by BrianHicks** [comment]
BTW: I already know that this doesn't upgrade cleanly. I want to get the PR reviewed before I go any further (Marathon). After those are both done, I will write an upgrade playbook.

**Comment by ryane** [comment]
Can we get the relevant commits from https://github.com/CiscoCloud/microservices-infrastructure/commits/feature/upgrade-marathon-mesos in here so that the UIs will work with the latest versions of marathon and mesos?

**Comment by TanyaCouture** [comment]
Tests passed:
Vagrant
AWS

**Comment by BrianHicks** [comment]
@ryane probably, should just be the three most recent, right? (f863077691eb3002bc91de52e6cd0c97f8d3f4ff, 622028372ac34c060c311c89337548419d28735a, and b562e10d7df0324b756c9863ff4308dd38692196)

**Comment by BrianHicks** [comment]
@TanyaCouture thanks!

**Comment by ryane** [comment]
@BrianHicks that's right

**Comment by BrianHicks** [comment]
I'm going to close this PR and open a new one when all the fixes and upgrades are in place. Thanks again for testing, @TanyaCouture

**Pull request closed without merging**
