### PR TITLE
mi-deploy: Generate security.yml and terraform.yml every time

### PR DESCRIPTION
**Pull request by siddharthist**
Update README with new information
Fixes issue #718

### CODE REVIEW

**Comment by stevendborrelli** [comment]
@eirslett any feedback on this?

**Comment by eirslett** [comment]
For running a production cluster, of course we need to use the same security.yml every time. But since mi-deploy is for integration tests, not production clusters, I guess it should be fine. Though when we run integration tests, we disable calico and add some custom options, I'm not sure if that would still work with this change.
We'll probably use our fork of mi-deploy for deploying the cluster for now, and then sit on the fence for what's coming with the mantl CLI stuff. Or write our own deployer.

**Comment by stevendborrelli** [comment]
@eirslett thanks for the feedback. I think we need to be building tools that multiple people use. We'd rather not have to force you to fork one of our tools. 

@siddharthist is this something that can be made optional?

**Comment by siddharthist** [comment]
@stevendborrelli Absolutely! I'll change that ASAP.

**Comment by siddharthist** [comment]
Now it should only generate new ones if you don't have `terraform.yml` or `security.yml` and `ssl/` in your `tf-files/` directory. Does that work for you @eirslett?

**Comment by eirslett** [comment]
Sure! Sounds like a good solution! (But should probably be documented, and maybe even unit-tested)

**Comment by ohal** [comment]
test this please

**Comment by siddharthist** [comment]
Is anything blocking this? It's well tested, and should be ready to merge. Documentation has been provided.

**Pull request merged**
