### PR TITLE
Feature/host ssl

### PR DESCRIPTION
**Pull request by ChrisAubuchon**
This moves the generation of the SSL certificates to the hosts.

### CODE REVIEW

**Comment by siddharthist** [comment]
Test results:
Working:
 * Openstack
Failing: 
 * AWS
 * GCE

**Comment by ryane** [comment]
lgtm too. working on aws.

**Comment by stevendborrelli** [comment]
I'd like to do a security review on our SSL generation before we merge it. Still looking for an outside resource.

**Comment by eirslett** [comment]
How would you use this to deploy your own out-of-band-generated SSL certificates? (You might want to use your own GoDaddy-signed certificate for the nginx frontend)

**Comment by stevendborrelli** [comment]
@eirslett we're leaning towards using Vault to distribute secrets to the systems. I'm trying to get a couple of new folks on the project working on this in the next couple of weeks. .

**Comment by siddharthist** [comment]
The branch feature/vault-ssl makes this work obsolete, let's close this when a PR for that one is open.

**Comment by siddharthist** [comment]
Incorporated/obsoleted by #1045

**Pull request closed without merging**
