### PR TITLE
Attempt to fix #234

### PR DESCRIPTION
**Pull request by andreimc**
Hey guys,

Due to the Nginx container issue you can not disable ssl for consul

This is not a great solution it should be fixed at container level and pass something like CONSUL_SSL='-ssl' if consul ssl is enabled.

### CODE REVIEW

**Comment by ChrisAubuchon** [comment]
What configuration are you running? Have you merged in feature/nginx-ssl?

**Comment by andreimc** [comment]
@ChrisAubuchon I am pushing SSL up to LB and I disable SSL in the network (since it will be private) I am just basically trying to have unsecure network inside the VPC and the way the nginx container is designed if you mount the volumes with the certs it will call consul over https

I closed this cause my master was tainted will do some further testing today without it and if it still is an issue I will fix it at nginx container level and do a pull request there

**Comment by andreimc** [comment]
subnet


My subnet looks like this and it will be made private only thing visible from the outside is the LB which only accepts 443 80 traffic

**Comment by keithchambers** [comment]
@andreimc we will begin developing support for AWS on Monday. I'd really like to understand your use cases and get your feedback. Can you email me at kechambe@cisco.com? Thanks!

**Pull request closed without merging**
