### PR TITLE
Kafka-mesos: remove host fqdn dependency

### PR DESCRIPTION
**Pull request by Y4Rv1K**
Start brockers using consul-dns record instead hardcoded node fqdn

### CODE REVIEW

**Comment by Y4Rv1K** [comment]
@AndriiOmelianenko  Please test this branch

**Comment by Y4Rv1K** [comment]
@AndriiOmelianenko Please test it. 
@OleksandrBerchenko please review it

**Comment by ohal** [comment]
@jenkins test this please

**Comment by ohal** [comment]
@jenkins test this please

**Comment by AndriiOmelianenko** [comment]
@Y4Rv1K @OleksandrBerchenko 
Tests passed successfully.

**Comment by Y4Rv1K** [comment]
@OleksandrBerchenko please review it and merge

**Comment by ohal** [comment]
@jenkins retest this please

**Comment by ohal** [comment]
@jenkins retest this please

**Comment by ohal** [comment]
@jenkins ok to test

**Comment by Y4Rv1K** [comment]
@OleksandrBerchenko Please review this PR.

**Comment by OleksandrBerchenko** [comment]
Looks good to me.  Merging.

**Pull request merged**
