### PR TITLE
Two VM Vagrant configuration

### LINKED ISSUE #499: provision Vagrant with Ansible directly
For stuff like #256, we'll want to provision machines in parallel. So we should have another inventory plugin that finds the files Vagrant generates in `.vagrant` and connects Ansible to them without too much hassle.

### PR DESCRIPTION
**Pull request by siddharthist**
This:
 * Creates two nodes through Vagrant
 * Provisions both from the leader node
 * Enhances our provisioning script for speed and reslience

It fixes: 
 * #674 
 * #888 
 * #256 
 * #930 

and makes progress on/maybe fixes #499, #877, #179, which all need more testing. 

Next steps/new issues:
 1. Vagrant GlusterFS support
 2. Vagrant LVM support
 3. Update packer scripts/mi box
 4. Fix this very rare error: http://pastebin.com/csrNsK07
 5. Configurable number of VMs with terraform.py style dynamic inventory

### CODE REVIEW

**Comment by ChrisAubuchon** [comment]
Do we want to require people to create their own `terraform.yml`? The goal of our previous method was to allow people to `git clone https://github.com/CiscoCloud/microservices-infrastructure; vagrant up` without having to do any configuration.

**Comment by siddharthist** [comment]
@ChrisAubuchon That's a good point, we can actually use terraform.sample.yml now that Gluster has been made optional. I'll fix that.

**Comment by stevendborrelli** [comment]
Got a bunch of these errors, maybe we need to ignore the `.terraform` directory if a user has one? 

```
symlink has no referent: "/Users/steve/customers/merge-tests/0.6/.terraform/modules/e72067befd314edae9385ed5cfd2de7d"
symlink has no referent: "/Users/steve/customers/merge-tests/0.6/.terraform/modules/fe4d78c59130ca98fabd595dd9d57dfe"
```

**Comment by stevendborrelli** [comment]
Ok, once I delete the `.terraform` directory, I get: 

```
==> control: Couldn't find /vagrant/terraform.yml, please create one.
==> control: + '[' '!' -f /vagrant/terraform.yml ']'
==> control: + echo 'Couldn'\''t find /vagrant/terraform.yml, please create one.'
==> control: + exit 1
```

**Comment by ChrisAubuchon** [comment]
First error message looks like an rsync issue. With respect to the second error, you have to create a `terraform.yml` file.

**Comment by ChrisAubuchon** [comment]
The packer build uses `vagrant.yml`. We should update the packer build before merging.

**Comment by siddharthist** [comment]
@stevendborrelli The first error is caused by Vagrant's rsync (shared folder) configuration, which copies in files referred to by symlinks. The second one is fixed in the most recent commit, so users won't have to create a `terraform.yml`. I'll learn Packer and update the build ASAP :)

**Comment by ChrisAubuchon** [comment]
@siddharthist I'll take the packer build. I'm already trying to add `playbooks/upgrade-packages.yml` to the base build

**Comment by siddharthist** [comment]
Closing this in favor of #942, a more complete solution.

**Pull request closed without merging**
