### PR TITLE
Issue #500 - docker log rotation

### PR DESCRIPTION
**Pull request by SillyMoo**
Force docker to use syslog log driver, and then use logrotate to rotate the syslog logs.

As per Issue https://github.com/CiscoCloud/microservices-infrastructure/issues/500.

### CODE REVIEW

**Comment by ohal** [comment]
@ test this please

**Comment by ohal** [comment]
@ ok to test

**Comment by ohal** [comment]
test this please

**Comment by ohal** [comment]
test this please

**Comment by ohal** [comment]
test this please

**Comment by ohal** [comment]
test this please

**Comment by ohal** [comment]
test this please

**Comment by ohal** [comment]
test this please

**Comment by eirslett** [comment]
Maybe make the log driver configurable? The fluentd driver seems promising.

**Comment by SillyMoo** [comment]
@eirslett There is already an Issue for that, #646, this PR is just for #500 and is just to address immediate issues with the current mechanism, i.e to buy time until #646 can be designed and implemented.

**Pull request merged**
