### PR TITLE
Enable different flavors for control and resource nodes

### PR DESCRIPTION
**Pull request by kenjones-cisco**

### CODE REVIEW

**Comment by keithchambers** [comment]
@kenjones-cisco I'll spend some time on this PR today. I'm thinking we can achieve the same result with fewer changes perhaps. I'll ping you later for feedback. :+1:

**Comment by stevendborrelli** [comment]
We could look at group vars: http://docs.ansible.com/intro_inventory.html#group-variables in ansible.

**Comment by keithchambers** [comment]
@stevendborrelli I was thinking along the same lines.  So perhaps the inventory looks like the following?

```
...

# resource nodes
[consul_clients]
host-[04:05]
host-[09:10]

[consul_clients:vars]
os_flavor_ram=16384
os_flavor_include=XLarge

...
```

**Comment by stevendborrelli** [comment]
@keithchambers yup...that will map to terraform too. 

We'd probably want to put resources on either the mesos leaders or consul servers, and the mesos followers (which will need to be big).

The nice thing about group vars is later we can break out server groups to things like SSD (or Kafka nodes), and then use that var 'ssd` as a mesos slave attritbute.

**Comment by kenjones-cisco** [comment]
Since the openstack/provision-hosts.yml refers to "hosts: all" would the group_vars be picked up at provisioning time?

**Comment by stevendborrelli** [comment]
@kenjones-cisco we'll need to test it. In the past, I overrode those vars on a per-host basis and it worked. (i.e. `host-01 os_flavor_include=xxxx`)

**Comment by kenjones-cisco** [comment]
That was part of the motivation of the new group and updating the provision playbook to avoid having to do per host configuration especially if you need to create large clusters.

**Comment by stevendborrelli** [comment]
Sorry if I was unclear, in the past I had used host-level stuff, so I am expecting group-level vars to work.

**Comment by keithchambers** [comment]
I just tested extending ```inventory/group_vars/consul_clients``` to include the following and it works! :+1: 

```
consul_is_server: no
os_flavor_ram: 16384
os_flavor_include: XLarge
```

**Comment by keithchambers** [comment]
@kenjones-cisco and I had a quick IM conversation and he's cool with this workaround.  Closing.

**Pull request closed without merging**
