### PR TITLE
remove .consul hardcodes

### LINKED ISSUE #1029: consul_dns_domain should be configurable everywhere
There are several places where the consul dns domain is hardcoded to `.consul` instead of relying on the `consul_dns_domain` variable.

- [x] traefik
- [x] glusterfs
- [x] mantl-api marathon url
- [x] various docs

### PR DESCRIPTION
**Pull request by ryane**
fixes #1029

### CODE REVIEW

**Comment by siddharthist** [comment]
LGTM!

**Comment by siddharthist** [comment]
Tested and working on Openstack, I was able to chage `.consul` dns names to an alternate name, and the endpoints responded appropriately.

**Comment by ryane** [comment]
thanks for testing! i will rebase and merge this but I want to wait for #1045 since it changes how `consul_dns_domain` is set

**Comment by siddharthist** [comment]
Ready for testing @sehqlr @TanyaCouture

**Comment by TanyaCouture** [comment]
Changed consul_dns_domain default and successfully deployed with aws.

**Comment by ryane** [comment]
thanks!

**Pull request merged**
