### PR TITLE
marathon: lock down config directory

### LINKED ISSUE #1047: more secure permissions on /etc/marathon/*
/etc/marathon contains files with sensitive information. Permissions on these files should be 600. see #793 for reference.

### PR DESCRIPTION
**Pull request by BrianHicks**
Fixes #1047

### CODE REVIEW

**Comment by ryane** [comment]
it looks like this is missing `path`:

```
failed: [resching-aws-control-02] => {"failed": true}
msg: missing required arguments: path
```

Also, setting 0600 on /etc/marathon breaks the distributive checks. I opened #1050 with a workaround that moves the sensitive files into /etc/marathon/apps.

**Comment by BrianHicks** [comment]
Ha! That's what I get for thinking I can sneak this in without testing it myself. I'll fix it now. :)

**Comment by BrianHicks** [comment]
Actually, it looks like #1050 may resolve this anyway. Should we close?

**Comment by ryane** [comment]
yep, #1050 should resolve this

**Pull request closed without merging**
