### PR TITLE
Fixes for lvm setup

### PR DESCRIPTION
**Pull request by avnik**

### CODE REVIEW

**Comment by siddharthist** [comment]
Tested on DO

**Comment by ryane** [comment]
looks good on GCE

**Comment by ryane** [comment]
+1 on AWS

**Comment by sehqlr** [comment]
I ran this on OpenStack, and I got an error:
```
TASK: [glusterfs | create container volume] ***********************************
failed: [shatfiel-lon1-test-control-01] => {"changed": true, "cmd": ["/etc/glusterfs/glus
ter_volume.sh", "container-volumes"], "delta": "0:00:00.026292", "end": "2015-11-13 16:51
:32.791160", "rc": 1, "start": "2015-11-13 16:51:32.764868", "warnings": []}
stderr: + NAME=container-volumes
+ gluster volume list
+ grep -q container-volumes
No volumes present in cluster
+ gluster volume create container-volumes replica 1 shatfiel-lon1-test-control-01.node.co
nsul:/mnt/glusterfs/container-volumes
replica count should be greater than 1
Usage: volume create <NEW-VOLNAME> [stripe <COUNT>] [replica <COUNT> [arbiter <COUNT>]] [
disperse [<COUNT>]] [disperse-data <COUNT>] [redundancy <COUNT>] [transport <tcp|rdma|tcp
,rdma>] <NEW-BRICK>?<vg_name>... [force]

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
mesos | create zookeeper acl ------------------------------------------- 13.97s
marathon | create zookeeper acl ---------------------------------------- 12.33s
chronos | create zookeeper acl ----------------------------------------- 11.84s
marathon | wait for marathon to listen ---------------------------------- 8.76s
check for security ------------------------------------------------------ 7.56s
common | install system utilities --------------------------------------- 5.50s
consul-template | install consul-template ------------------------------- 4.28s
dnsmasq | install packages ---------------------------------------------- 4.18s
consul | install consul ------------------------------------------------- 3.91s
vault | install vault --------------------------------------------------- 3.72s
           to retry, use: --limit @/home/shatfiel/terraform.sample.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=0
shatfiel-lon1-test-control-01 : ok=237  changed=30   unreachable=0    failed=1
shatfiel-lon1-test-worker-001 : ok=131  changed=9    unreachable=0    failed=0
```

**Comment by siddharthist** [comment]
See #674

**Comment by sehqlr** [comment]
Right. I'm running the test again, with two control nodes

**Comment by sehqlr** [comment]
I ran `terraform.sample.ml` on my OpenStack cluster, and the step that failed the first time worked. So, +1 for OpenStack

**Pull request merged**
