### PR TITLE
Use our own Mesos and Marathon packages

### PR DESCRIPTION
**Pull request by BrianHicks**
This PR replaces Mesosphere's Mesos and Marathon packages with our own, in preparation for future releases where we'll have our own modules compiled in by default. It also simplifies the packaging structure, and includes @ryane's commits for updating the UI to work with the latest version of Mesos.

I've tested on DO, @TanyaCouture has tested Vagrant and AWS. However, merging this means we will need to upload a fresh vagrant image.

### CODE REVIEW

**Comment by BrianHicks** [comment]
Tested on GCE, works just fine there.

**Comment by ryane** [comment]
@BrianHicks, @stevendborrelli, do we need to make sure the issue fixed by #916 (see #914) is integrated in this PR?

**Comment by ryane** [comment]
@BrianHicks The upgrade playbook is failing for me. on an existing cluster, I ran `ansible-playbook -e @security.yml playbooks/upgrade-mesos-marathon.yml`. The upgrade completed on all worker nodes. But it failed on the first control node:

```
NOTIFIED: [wait for marathon to listen] ***************************************
failed: [resching-gce-control-01] => {"changed": true, "cmd": ["/usr/local/bin/marathon-wait-for-listen.sh"], "delta": "0:02:00.202787", "end": "2016-01-07 01:58:33.895468", "rc": 2, "start": "2016-01-07 01:56:33.692681", "warnings": []}
```

on that node, marathon was unable to start due to the following:

```
marathon[24707]: [scallop] Error: Bad arguments for option 'event_subscriber': 'http_callback http_callback' - you should provide exactly one argument for this option
```

It looks like that variable value is getting duplicated because of `/etc/marathon/conf/event_subsciber`. Should we move or remove /etc/marathon/conf as part of the upgrade?

**Comment by BrianHicks** [comment]
Oops, yes we should. I was removing all of /etc/marathon and it caused other problems. I guess leaving it in is too far the other direction.

**Comment by ryane** [comment]
also, can we add some documentation for the upgrade procedure? After running the upgrade playbook, what are the next steps? 

For example, I noticed that after the upgrade, I had both mesos-agent and mesos-slave services running on worker nodes and tasks were not running correctly. I was able to get past it by rebooting the worker nodes (may have been overkill) so it would be good to document the full procedure.

**Comment by siddharthist** [comment]
Where are these packages from? I see the bintray URLs for the RPMs, but is the source available somewhere?

**Comment by BrianHicks** [comment]
@ryane @stevendborrelli: Changes from #916 are included in this PR. Only change needed was dd0a87b

@ryane: the upgrade script now removes /etc/marathon/conf (3281677), and the process is documented (c2a3264)

@siddharthist: github.com/asteris-llc/mesos-packaging

**Comment by ryane** [comment]
@BrianHicks, apologies if I missed it, but aren't we still missing a step to ensure that the mesos-slave service is stopped on worker nodes? without this, post-upgrade you end with mesos-agent and mesos-slave services running and tasks fail to start successfully (notably mesos-consul)

**Comment by BrianHicks** [comment]
That should be taken care of by removing the old Mesos package, 
shouldn’t it? Regardless, we can certainly stop it before removal.

**Comment by ryane** [comment]
No, at least as of cd42f7b it doesn't. The mesos-slave services remain running

**Comment by BrianHicks** [comment]
Interesting! 77e286c should fix that.

**Comment by ryane** [comment]
lgtm. successfully tested a clean install and an upgrade from 0.5.1

**Pull request merged**
