### PR TITLE
Feature/calico role

### PR DESCRIPTION
**Pull request by loshkovskyi**
This is the new PR to add Calico role to M-I. I have synced with the latest master and tested deployments on OpenStack, GCE and DigitalOcean.

### CODE REVIEW

**Comment by ryane** [comment]
this is working well for me on gce

**Comment by ryane** [comment]
seems solid to me. tested without problems on gce, aws, do, and openstack platforms.

**Comment by eirslett** [comment]
This PR breaks Marathon support.
Marathon doesn't work with Mesos 0.23 yet, it only works with Mesos 0.22.1.

**Comment by stevendborrelli** [comment]
@eirslett thanks for reporting this issue.

**Comment by ryane** [comment]
Any details about what is not working? I did not run into any marathon issues with mesos 0.23.0. mesos-consul and marathon-consul run ok in marathon and I was also able to run some sample jobs (with and without enabling Calico networking). We might need to add more testing coverage if something is broken. @loshkovskyi did you see any problems with marathon on mesos 0.23.0?

oh and btw, did you enable the calico and etcd roles in terraform.yml (see `terraform.sample.yml`)? If not, you likely would see problems. I did just notice that our `vagrant.yml` is missing those roles so I created #661 for that

**Comment by loshkovskyi** [comment]
In fact, we've been deploying Mesos 0.23.0 for months and I didn't encounter any issues with it. Remember, we used to set `latest` when installing Mesos from Mesosphere repositories which implies installation of Mesos 0.23.0. This PR https://github.com/CiscoCloud/microservices-infrastructure/pull/618 is more about to start using versioning, not about any problems in Mesos. In addition, Calico can happily work with both Mesos 0.22.1 and 0.23.0 (with some configuration changes). I didn't include Calico in `vagrant.yml` on purpose, as for me it's a bit of overkill to use BGP in a single VM. Though, I'm always open to discussions.

**Comment by ryane** [comment]
Right.

RE: vagrant. I went ahead and added those roles b/c the vagrant build is
definitely broken without them right now. Any idea what needs to change so
that those roles are truly optional?

Ryan Eschinger | http://ryaneschinger.com
Phone: 347-394-2990
Skype: ryanesch

**Comment by ryane** [comment]
Looks like we shouldn't drop the `/etc/mesos-slave/executor_environment_variables` file when calico is not included. I suspect that might be the issue

**Comment by eirslett** [comment]
I disabled the calico stuff (hadn't tried it out yet) maybe that's the problem? I blamed it on Mesos 0.23 since there are some issues out there about Marathon not working with the latest Mesos version.
The strange thing is that both mesos-consul and marathon-consul ran fine on the cluster, but everything failed when I tried to deploy other Docker apps. And I was not able to restart or scale mesos-consul or marathon-consul (just testing to see what would happen), I suspect something with the executor failed. Marathon started the tasks, but they immediately failed; mesos showed no output in the stdout or stderr logs.
Just for testing, I started a new Marathon task with a `uris: ["http://www.example.com/index.html"]` setting to see what would happen. The mesos logs showed that Maration did indeed start the task (the file was downloaded) but then failed to run the docker container.
On problem I encountered with `/etc/mesos-slave/executor_environment_variables` is that Mesos 0.22.1 didn't recognize the option, and failed to start.

I'll try starting up everything again, with default settings and the Calico role enabled!

**Comment by eirslett** [comment]
I tried with Calico now + faking SoftLayer so it doesn't use private IPs. Now I'm at least able to deploy Docker containers. Looks like the problem is limited to docker container from private registries, that's maybe why you couldn't reproduce it! My failure was with private containers. Sorry! I'll look into why my previous PR for private docker hub support doesn't work from inside Mesos; looks like it's an issue with $HOME being set.

**Pull request merged**
