### PR TITLE
mesos: ensure quorum member count is persisted in /etc/mesos-master/quorum

### PR DESCRIPTION
**Pull request by abn**
This seems to be required for the cluster to show up correctly, encountered this when deploying 0.5.1. Not really sure if this was red-herring. Submitting PR for good measure.

### CODE REVIEW

**Comment by ryane** [comment]
thanks for this. on master and in the upcoming 0.6 release, we moved to different mesos packaging. And quorum is set here:

https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/mesos/templates/mesos-master.sysconfig.j2

I will close this but feel free to re-open if I missed something. Thanks again!

**Comment by abn** [comment]
@ryane using `{{ groups[mesos_leaders_group]|count // 2 + 1 }}` did not bring the cluster up correct. Had to use `{{ groups[mesos_leaders_group]|count }}`. Think the member count is expected here, but I am not sure about this one - someone more knowledgeable about this should confirm.

Might need to fix https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/mesos/templates/mesos-master.sysconfig.j2#L10

**Comment by abn** [comment]
@ryane  also note that `/etc/mesos/quorum` is different to what the `master-defaults.j2` was used for.

**Comment by ryane** [comment]
@abn what problems are you seeing when using `{{ groups[mesos_leaders_group]|count // 2 + 1 }}`? I don't see any obvious problems with clusters I have built from master and it seems that it is consistent with the mesos docs: http://mesos.apache.org/documentation/latest/configuration/. but, I don't have a ton of knowledge about this either. pinging @BrianHicks to see if he has any feedback.

**Comment by BrianHicks** [comment]
I don't, except that the `MESOS_QUORUM` in the sysconfig is the same as `/etc/mesos/quorum`. They're just two ways of saying the same thing.

@abn could you be a little more specific about what problem you're having? Quorum issues are tricky to debug, what exactly were you seeing?

**Comment by abn** [comment]
@BrianHicks the symptom was that the slaves never showed up on the mesos ui after play completion. Weird bit was that marathon seemed happy enough.

Tried a reboot - no luck, mesos-master restart - no luck, tried setting `/etc/mesos/quorum` to 2 (have 3 control nodes) - restarted still no slaves; and finally set it to 3 and restarted all slaves show up. This happened on 2 fresh installs. The latest one with the fix in, came up clean - am doing another clean run tomorrow can report back if it was a red herring.

**Comment by abn** [comment]
Closing the loop on this one. Spun 2 fresh clusters, slaves never showed - this time with quorum set to 3; but did show up correctly using 2. This implies that this was not the root cause.

**Pull request closed without merging**
