### PR TITLE
Host destroy issue with checking external storage

### PR DESCRIPTION
**Pull request by OleksandrBerchenko**

### CODE REVIEW

**Comment by Y4Rv1K** [comment]
looks ok

**Comment by Y4Rv1K** [comment]
@jenkins please test it

**Comment by AndriiOmelianenko** [comment]
@jenkins ok to test

**Comment by ohal** [comment]
@jenkins test this please

**Comment by ohal** [comment]
@jenkins ok to test

**Comment by AndriiOmelianenko** [comment]
@OleksandrBerchenko @Y4Rv1K 
Tests passed.

**Pull request merged**
