### PR TITLE
Feature/image build

### PR DESCRIPTION
**Pull request by keithchambers**
A step toward immutable deployments.  More work is needed but all the code in here should be high quality and anything that's not needs to be cleaned up before merging.

With this pull request we switch to use `CiscoCloud/microservices-infrastructure` as the base Vagrant box.  This box has all RPMs and containers pre-installed so the `vagrant up` takes 5-6 minutes vs 15-20.

We can iterate from here to further extend this to supporting AWS, GCE, and OpenStack.

[Review on Reviewable](https://reviewable.io/reviews/ciscocloud/microservices-infrastructure/253)

### CODE REVIEW

**Comment by keithchambers** [comment]
Thanks @ChrisAubuchon!

I don't fully understand the marathon restart logic but I'm sure you are right.  Do you mind correcting my code for me?

**Comment by keithchambers** [comment]
@ChrisAubuchon hmm I did a full deploy from scratch and all was working.  Let me test again.

**Comment by stevendborrelli** [comment]
Do we still have an issue with Vagrant? Would like to merge this today.

How do we test the vagrant issue?

**Comment by ChrisAubuchon** [comment]
No. I think I was on a bad branch. Re-pulled and it was fine.

**Comment by stevendborrelli** [comment]
The issue I am seeing is related to zookeeper, we'll be fixing it in another branch: https://github.com/asteris-llc/docker-zookeeper/issues/3

**Pull request merged**
