### PR TITLE
Feature/logstash role

### PR DESCRIPTION
**Pull request by Y4Rv1K**

### CODE REVIEW

**Comment by Y4Rv1K** [comment]
@loshkovskyi please review

**Comment by keithchambers** [comment]
@Y4Rv1K can you rebase this to master?

**Comment by loshkovskyi** [comment]
Please correct me if I'm wrong but you are asking me to merge 68 commits, whereas most of them has nothing to do with my branch. Please don't rebase. All of this should go to `qa/integration` for further testing. I will review your work tomorrow. Thanks.

**Comment by keithchambers** [comment]
Ahhh I missed that the PR is for CiscoCloud:feature/logstash-role.  My bad.

**Pull request closed without merging**
