### PR TITLE
Add Drone CI configuration

### PR DESCRIPTION
**Pull request by sehqlr**

### CODE REVIEW

**Comment by siddharthist** [comment]
I'm going to close this for now because we have some issues to work out with auth, and the builds are failing as well. We have a PR coming in for Travis soon, hopefully with Drone soon after.

**Comment by benschumacher** [comment]
Related in Drone: https://github.com/drone/drone/issues/1476

**Comment by siddharthist** [comment]
We also have a PR in for Drone plugin-based auth: https://github.com/drone/drone-exec/pull/28

**Comment by siddharthist** [comment]
Deleting this branch since we at least are waiting until Drone 0.5, which will have different auth mechanisms, and we use Travis for CI right now.

**Pull request closed without merging**
