### PR TITLE
Logstash logs to elasticsearch

### PR DESCRIPTION
**Pull request by jhftrifork**

### CODE REVIEW

**Comment by eirslett** [comment]
I guess that this requires elasticsearch to be running on the Mesos cluster first? It's already possible to configure the elasticsearch output in terraform.yml, this change isn't really needed. (But nice to have if Mantl has first-class support for ELK)

**Comment by jhftrifork** [comment]
@eirslett indeed it does. I'm working on this issue on https://github.com/CiscoCloud/alpha and I assume it will get merged here at some point.

**Comment by eirslett** [comment]
page not found... is that a private repo?

**Comment by corebug** [comment]
@eirslett yes, it's a private repo. I'm closing the PR by, the code will be PR'd together with ELK stack stuff.

**Pull request closed without merging**
