### PR TITLE
0.5.1 to 0.6 upgrade

### LINKED ISSUE #1003: upgrade path from 0.5.1 to 0.6
0.6 will include updated versions of marathon (0.13), mesos (0.25), and consul (0.6.3). We want to support an upgrade of an existing 0.5.1 cluster.

- [x] mesos/marathon: https://github.com/CiscoCloud/microservices-infrastructure/blob/master/playbooks/upgrade-mesos-marathon.yml
- [ ] consul upgrade
- [ ] vault (depending if https://github.com/CiscoCloud/microservices-infrastructure/tree/feature/vault-ssl makes it to this release)
- [ ] document upgrade process

### PR DESCRIPTION
**Pull request by ryane**
fixes #1003

this PR should be tested with a clean install and an upgrade from a cluster running 0.5.1. The upgrade instructions are included in `docs/upgrading/index.rst`. After upgrading, the cluster should still be healthy, Mesos should be on v0.25, Marathon on v0.13, and Consul on v0.6.3. ping @TanyaCouture @sehqlr

### CODE REVIEW

**Comment by siddharthist** [comment]
LGTM!

**Comment by siddharthist** [comment]
@ryane Why would this be tested with a clean install of 0.6? I don't see any changes except moving the Consul URLs, which really shouldn't have any effect that wouldn't be captured by and upgrade test.

**Comment by ryane** [comment]
@siddharthist since it did change the default consul playbook that is run as part of a clean install, I suggested it be tested. but, yeah, it seems unlikely that it would be break anything

**Comment by TanyaCouture** [comment]
Clean install and upgrade successful with deployment with DO
    Installed, all checks on UI passing
    Versions: Mesos v0.25, Marathon v0.13, Consul v0.6.3
    Ran playbooks/upgrade-0.5.1.yml and terraform.yml
    All checks on UI Passing and Versions the same as above
    
Upgrade from 0.5.1 successful with DO
    Installed from 0.5.1 tag, all checks on UI passing
    Versions: Mesos 0.23.0, Marathon 0.9.0, Consul 0.5.2
    Ran playbooks/upgrade-0.5.1.yml and terraform.yml
    All checks on UI passing and versions upgraded to: Marathon 0.13.0, Mesos 0.25.0, Consul 0.6.3

**Pull request merged**
