### PR TITLE
Feature/nginx ssl

### PR DESCRIPTION
**Pull request by ChrisAubuchon**
Change the nginx-marathon and nginx-mesos-leader containers to no longer use `--net=host`

### CODE REVIEW

**Comment by andreimc** [comment]
:+1:

**Comment by andreimc** [comment]
Hey @ChrisAubuchon you have some issues with this and the feature/granular-security

```
<<<<<<< HEAD
		listen {% raw %}{{ env "NGINX_PUBLIC_IP" }}{% endraw %}:{{ marathon_proxy_port }} {% if do_marathon_ssl|bool %}ssl{% endif %};
=======
		listen {{ marathon_proxy_port }} ssl;
>>>>>>> feature/nginx-ssl
```

I am guessing the result should be something like:

```
listen {{ marathon_proxy_port }}{% if do_marathon_ssl|bool %} ssl{% endif %};
```

or does it require the public ip?

**Comment by ChrisAubuchon** [comment]
Yeah. I have an updated feature/granular-security locally that I can push. I was thinking that we merge this one into master and then I fix the merge conflicts in feature/granular-security.

Your guess is a good one. That is what it will need to be.

**Comment by ChrisAubuchon** [comment]
Going to rebase

**Pull request closed without merging**
