### PR TITLE
Add collectd with docker plugin as host system service. In terms of #53 (fixed bugs)

### PR DESCRIPTION
**Pull request by corebug**
## collectd                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                              
Monitoring role for deploying and managing [collectd](https://collectd.org) service on host operating systems.                                                                                                                                                                
Sends collected metrics to user-defined (defaults/main.yml) host, those can be easily analyzed via Logstash.                                                                                                                                                                  
                                                                                                                                                                                                                                                                              
## User-customizable variables                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                              
You can use these variables (defaults/main.yml) to customize your collectd installation.                                                                                                                                                                                      
                                                                                                                                                                                                                                                                              
| var | description | default |                                                                                                                                                                                                                                               
|-----|-------------|---------|                                                                                                                                                                                                                                               
|`logging_host`|host to receive collectd's metrics over the network| {{ ansible_ssh_host }}|                                                                                                                                                                                  
|`logging_host_port`|port to receive collectd's metrics over the network| 25826|          
|`mesos_master_host`|host to get mesos master data from|localhost|
|`mesos_master_port`|mesos master http port|15050|
|`mesos_slave_host`|host to get mesos slave data from|localhost|
|`mesos_slave_port`|mesos slave http port|15050|
|`marathon_host`|host to get marathon data from|localhost|
|`marathon_port`|marathon http port|18080|
|`zookeeper_hosts`|hosts to get zookeeper metrics from|localhost|

### CODE REVIEW

**Comment by BrianHicks** [comment]
@corebug could you please convert the README to RST and add it to the docs site? The vars will need to match the format as well. The [Marathon README](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/marathon/README.rst) and [doc page](https://raw.githubusercontent.com/CiscoCloud/microservices-infrastructure/master/docs/components/marathon.rst) are probably good examples.

**Comment by corebug** [comment]
@BrianHicks sure, i'll get that done asap.

**Comment by corebug** [comment]
@BrianHicks @loshkovskyi all requested changes done.

**Comment by BrianHicks** [comment]
@corebug not quite, you still need to add a page under the doc tree. Under components should be fine. If you wouldn't mind while you're doing that, could you change the vars to description *then* default, as in the rest of the docs? Thanks.

**Comment by corebug** [comment]
@BrianHicks just pushed changed version.

**Comment by BrianHicks** [comment]
@corebog LGTM on docs :shipit:

**Comment by keithchambers** [comment]
@corebug I just did a fair amount of refactoring.
* Rename role from `monitoring` to `collectd`
* Move services/role specific collectd plugins and configs in to the corresponding ansible role (e.g., `docker`, `mesos`, `marathon`, `zookeeper`)
* Added more default metrics
* Remove all the configurable parameter in ansible to simplify (since we don't need them yet)
* Remove "monitoring" docs since their are no configurable parameters

I think this is ready for final testing and then merging.

**Comment by BrianHicks** [comment]
@keithchambers this should have documentation even without the parameters to improve discoverability of components.

**Comment by keithchambers** [comment]
@BrianHicks yea you are totally right. :+1: I'll add them back with appropriate edits.

Also, I think we need to break this in to smaller PRs and start merging.  I'll create a PR for a collectd role this morning.

**Comment by keithchambers** [comment]
I'll update this comment as a create the smaller PRs:
* collectd base: https://github.com/CiscoCloud/microservices-infrastructure/pull/335
* Docker:
* Mesos:
* Marathon:
* ZooKeeper:

**Comment by corebug** [comment]
Currently we have: 
* collectd base: https://github.com/CiscoCloud/microservices-infrastructure/pull/335
* Docker: https://github.com/CiscoCloud/microservices-infrastructure/pull/352
* Mesos: https://github.com/CiscoCloud/microservices-infrastructure/pull/347
* Marathon: https://github.com/CiscoCloud/microservices-infrastructure/pull/345
* ZooKeeper: https://github.com/CiscoCloud/microservices-infrastructure/pull/346

**Comment by corebug** [comment]
Moved rebased code to https://github.com/CiscoCloud/microservices-infrastructure/pull/417

**Pull request closed without merging**
