### PR TITLE
clean up security-setup options

### PR DESCRIPTION
**Pull request by BrianHicks**
Fixes issues raised in #239, and documented in #247 and #248. Current help string:

```
usage: set up authentication and security for various components

optional arguments:
  -h, --help            show this help message and exit
  --change-admin-password
                        change admin password during this run (default: False)

Broad Disable Options:
  disable security for entire components. This overrides any more specific options set from the sections below.

  --disable             disable all security. This overrides everything. (default: False)
  --consul CONSUL       Enable Consul security. This overrides all other Consul options. (default: True)
  --mesos MESOS         Enable Mesos security. This overrides all other Mesos options. (default: True)
  --marathon MARATHON   Enable Marathon security. This overrides all other Marathon options. (default: True)
  --iptables IPTABLES   Use iptables rules. This overrides all other options related to iptables. (default: True)

SSL Certificate Options:
  a certificate authority will be set up, and certificates will be issued using these options

  --cert-country CERT_COUNTRY
                        certificate country (default: US)
  --cert-state CERT_STATE
                        certificate state/province (default: New York)
  --cert-locality CERT_LOCALITY
                        certificate locality/city (default: Anytown)
  --cert-organization CERT_ORGANIZATION
                        certificate organization (default: Example Company Inc)
  --cert-unit CERT_UNIT
                        organizational unit inside of organization (default: Operations)
  --cert-email CERT_EMAIL
                        contact email for organizational unit (default: operations@example.com)
  --consul-location CONSUL_LOCATION
                        internal name for Consul certificate, will be used as common name (default: consul.service.consul)
  --nginx-location NGINX_LOCATION
                        internal name for Nginx proxies, will be used as common name (default: *.service.consul)
  --no-verify-certificates
                        skip verifying certificates as part of setup process (default: False)

Consul Options:
  enable and disable auth components of Consul

  --consul-auth DO_CONSUL_AUTH
                        enable Consul auth (default: True)
  --consul-ssl DO_CONSUL_SSL
                        enable Consul auth (default: True)
  --consul-acl DO_CONSUL_ACL
                        enable Consul ACLs (default: True)

Mesos Options:
  enable and disable auth components of Mesos

  --mesos-ssl DO_MESOS_SSL
                        enable Mesos SSL (default: True)
  --mesos-auth DO_MESOS_AUTH
                        enable Mesos authentication (default: True)
  --mesos-framework-auth DO_MESOS_FRAMEWORK_AUTH
                        enable Mesos framework authentication (default: True)
  --mesos-follower-auth DO_MESOS_FOLLOWER_AUTH
                        enable Mesos follower authentication (default: True)
  --mesos-iptables DO_MESOS_IPTABLES
                        enable Mesos iptables rules (default: True)

Marathon Options:
  enable and disable auth components of Marathon

  --marathon-ssl DO_MARATHON_SSL
                        enable Marathon SSL (default: True)
  --marathon-auth DO_MARATHON_AUTH
                        enable Marathon authentication (default: True)
  --marathon-iptables DO_MARATHON_IPTABLES
                        enable Marathon iptables rules (default: True)
```

### CODE REVIEW

**Comment by kenjones-cisco** [comment]
@BrianHicks You import the `string` module but in the function bool_opt you have a parameter also named `string`. Might be prudent to avoid using variables that are also module names.

In python no need to use `len(var) > 0` as `not var` will determine if the variable has any value.

**Comment by BrianHicks** [comment]
@kenjones-cisco fixed the first concern in 278f70f

`not var` is implicit truthiness, and since "explicit is better than implicit" I think we'd better leave the check as-is.

**Comment by kenjones-cisco** [comment]
In python it is not considered implicit and part of standard PEP8, (https://www.python.org/dev/peps/pep-0008/#programming-recommendations).

Just sharing the information, the var name was the more pressing item.

**Comment by keithchambers** [comment]
Let's do the following:
* Add `--enable`             enable all security. This overrides everything.`
* Remove ` (default: False)` from the `--disable` description
* Change `Broad Disable Options:` to read `Broad Options:`
* Add a `Examples:` section at the bottom with 3-4 examples

**Comment by BrianHicks** [comment]
So if I'm understanding you correctly, the hierarchy of overrides should be:

 1. `--enable`
 2. `--disable`
 3. `--{component}=false`
 4. individual flags like `--mesos-follower-auth`

Changing the section name and adding usage should be fairly easy. Removing *only one* default is a little tricky, but I'll see what I can do. How important is that to you?

**Comment by BrianHicks** [comment]
OK, after the changes I just pushed we've got:

```
usage: set up authentication and security for various components

optional arguments:
  -h, --help            show this help message and exit
  --change-admin-password
                        change admin password during this run (default: False)

Broad Options:
  disable security for entire components. This overrides any more specific options set from the sections below.

  --enable ENABLE       enable all security. This overrides everything. (default: True)
  --consul CONSUL       Enable Consul security. This overrides all other Consul options. (default: True)
  --mesos MESOS         Enable Mesos security. This overrides all other Mesos options. (default: True)
  --marathon MARATHON   Enable Marathon security. This overrides all other Marathon options. (default: True)
  --iptables IPTABLES   Use iptables rules. This overrides all other options related to iptables. (default: True)

SSL Certificate Options:
  a certificate authority will be set up, and certificates will be issued using these options

  --cert-country CERT_COUNTRY
                        certificate country (default: US)
  --cert-state CERT_STATE
                        certificate state/province (default: New York)
  --cert-locality CERT_LOCALITY
                        certificate locality/city (default: Anytown)
  --cert-organization CERT_ORGANIZATION
                        certificate organization (default: Example Company Inc)
  --cert-unit CERT_UNIT
                        organizational unit inside of organization (default: Operations)
  --cert-email CERT_EMAIL
                        contact email for organizational unit (default: operations@example.com)
  --consul-location CONSUL_LOCATION
                        internal name for Consul certificate, will be used as common name (default: consul.service.consul)
  --nginx-location NGINX_LOCATION
                        internal name for Nginx proxies, will be used as common name (default: *.service.consul)
  --no-verify-certificates
                        skip verifying certificates as part of setup process (default: False)

Consul Options:
  enable and disable auth components of Consul

  --consul-auth DO_CONSUL_AUTH
                        enable Consul auth (default: True)
  --consul-ssl DO_CONSUL_SSL
                        enable Consul auth (default: True)
  --consul-acl DO_CONSUL_ACL
                        enable Consul ACLs (default: True)

Mesos Options:
  enable and disable auth components of Mesos

  --mesos-ssl DO_MESOS_SSL
                        enable Mesos SSL (default: True)
  --mesos-auth DO_MESOS_AUTH
                        enable Mesos authentication (default: True)
  --mesos-framework-auth DO_MESOS_FRAMEWORK_AUTH
                        enable Mesos framework authentication (default: True)
  --mesos-follower-auth DO_MESOS_FOLLOWER_AUTH
                        enable Mesos follower authentication (default: True)
  --mesos-iptables DO_MESOS_IPTABLES
                        enable Mesos iptables rules (default: True)

Marathon Options:
  enable and disable auth components of Marathon

  --marathon-ssl DO_MARATHON_SSL
                        enable Marathon SSL (default: True)
  --marathon-auth DO_MARATHON_AUTH
                        enable Marathon authentication (default: True)
  --marathon-iptables DO_MARATHON_IPTABLES
                        enable Marathon iptables rules (default: True)

Examples:

  ./security-setup
                        enable or re-enable all security options
  ./security-setup --enable=false
                        disable all security options
  ./security-setup --iptables=false --consul-ssl=false
                        disable iptables rules and Consul SSL
  ./security-setup --change-admin-password --enable=true
                        explicitly enable or re-enable every service (any
                        other disables will be ignored) and re-prompt for
                        the admin password.
```

Does that look good to everybody? Specifically, do any of these examples need to change?

**Comment by keithchambers** [comment]
@BrianHicks can you change ```disable security for entire components``` to ```enable and disable security for entire components``` ?

Otherwise LGTM!

**Pull request merged**
