### PR TITLE
GlusterFS fixes

### PR DESCRIPTION
**Pull request by BrianHicks**
- adds health checks for the Gluster daemon, the volumes, and the mounts
- reduces install target to only the packages necessary to run Gluster (`glusterfs-server` and `glusterfs-fuse` which handle their own dependencies)
- add a wait for port after starting glusterd
- checks that peers are properly setting up before proceeding with brick and volume creation

And a few side things I needed while doing this work:

- tag all the lvm tasks with `lvm`
- drop the requirement of a tty to use sudo. It was the only way I could find to write a proper healthcheck. All SSH clients *should* be allocating a tty anyway.

This has stabilized deployments for me (I've tested several clusters from scratch on GCE, where I saw it most often.) I'd appreciate other people's help in testing the rest of our deploy targets.

There are a few issues left to be addressed. I'm going to try and pick off #872 and #849. It already should address #868, which is what I'd like help testing.

### CODE REVIEW

**Comment by ryane** [comment]
I had a successful build with gce but failed builds on aws and digitalocean. in both cases, the issue is that the glusterfs install cannot recover after unrelated failures. info dump below:

on aws. 1st ansible run:

```
NOTIFIED: [marathon | wait for marathon to listen] ****************************
changed: [resching-aws-control-03]
changed: [resching-aws-control-02]
failed: [resching-aws-control-01] => {"changed": true, "cmd": ["/usr/local/bin/marathon-wait-for-listen.sh"], "delta": "0:02:00.244880", "end": "2015-12-01 20:34:07.914423", "rc": 2, "start": "2015-12-01 20:3
2:07.669543", "warnings": []}

...

TASK: [glusterfs | create container volume] ***********************************
failed: [resching-aws-control-02] => (item={'mount': '/mnt/container-volumes', 'name': 'container-volumes'}) => {"changed": true, "cmd": ["/etc/glusterfs/gluster_volume.sh", "container-volumes"], "delta": "0:00:00.033881", "end": "2015-12-01 20:38:48.241708", "item": {"mount": "/mnt/container-volumes", "name": "container-volumes"}, "rc": 1, "start": "2015-12-01 20:38:48.207827", "warnings": []}
stderr: + NAME=container-volumes
+ gluster volume list
+ grep -q container-volumes
No volumes present in cluster
+ gluster volume create container-volumes replica 3 resching-aws-control-01.node.consul:/mnt/glusterfs/container-volumes resching-aws-control-02.node.consul:/mnt/glusterfs/container-volumes resching-aws-control-03.node.consul:/mnt/glusterfs/container-volumes
volume create: container-volumes: failed: Host resching-aws-control-01.node.consul is not in 'Peer in Cluster' state

FATAL: all hosts have already failed -- aborting
```

Marathon failed on a single control node; subsequently the glusterfs install failed.

next ansible run:

```
TASK: [glusterfs | probe servers] *********************************************
changed: [resching-aws-control-01] => (item=resching-aws-control-01)
failed: [resching-aws-control-01] => (item=resching-aws-control-02) => {"changed": true, "cmd": ["gluster", "peer", "probe", "resching-aws-control-02.node.consul"], "delta": "0:00:00.044779", "end": "2015-12-01 20:54:49.962421", "item": "resching-aws-control-02", "rc": 1, "start": "2015-12-01 20:54:49.917642", "warnings": []}
stderr: peer probe: failed: Probe returned with Transport endpoint is not connected
failed: [resching-aws-control-01] => (item=resching-aws-control-03) => {"changed": true, "cmd": ["gluster", "peer", "probe", "resching-aws-control-03.node.consul"], "delta": "0:00:00.072701", "end": "2015-12-01 20:54:51.486686", "item": "resching-aws-control-03", "rc": 1, "start": "2015-12-01 20:54:51.413985", "warnings": []}
stderr: peer probe: failed: Probe returned with Transport endpoint is not connected

FATAL: all hosts have already failed -- aborting
```

we get past the marathon issue but glusterfs is in a bad state.

---

digital ocean. 1st ansible run:

```
TASK: [consul | wait for leader] **********************************************
changed: [resching-do-control-03]
changed: [resching-do-worker-001]
changed: [resching-do-control-01]
changed: [resching-do-control-02]
changed: [resching-do-worker-002]
changed: [resching-do-edge-02]
failed: [resching-do-worker-003] => {"changed": true, "cmd": ["/usr/local/bin/consul-wait-for-leader.sh"], "delta": "0:00:31.102004", "end": "2015-12-01 20:52:30.702071", "rc": 1, "start": "2015-12-01 20:51:5
9.600067", "warnings": []}
stdout: No Consul leader elected in 30 seconds
changed: [resching-do-edge-01]
changed: [resching-do-worker-004]
```

There were no failures after this. However, when running ansible a 2nd time in order to get resching-do-worker-003 fully provisioned, I get the following:

```
TASK: [glusterfs | create mount points for volumes] ***************************
changed: [resching-do-worker-003] => (item={'mount': '/mnt/container-volumes', 'name': 'container-volumes'})
ok: [resching-do-worker-002] => (item={'mount': '/mnt/container-volumes', 'name': 'container-volumes'})
ok: [resching-do-worker-004] => (item={'mount': '/mnt/container-volumes', 'name': 'container-volumes'})
ok: [resching-do-worker-001] => (item={'mount': '/mnt/container-volumes', 'name': 'container-volumes'})

TASK: [glusterfs | mount volumes] *********************************************
ok: [resching-do-worker-002] => (item={'mount': '/mnt/container-volumes', 'name': 'container-volumes'})
ok: [resching-do-worker-004] => (item={'mount': '/mnt/container-volumes', 'name': 'container-volumes'})
ok: [resching-do-worker-001] => (item={'mount': '/mnt/container-volumes', 'name': 'container-volumes'})
failed: [resching-do-worker-003] => (item={'mount': '/mnt/container-volumes', 'name': 'container-volumes'}) => {"failed": true, "item": {"mount": "/mnt/container-volumes", "name": "container-volumes"}}
msg: Error mounting /mnt/container-volumes: Mount failed. Please check the log file for more details.
```

Here is the log file:

```
sudo cat /var/log/glusterfs/mnt-container-volumes.log
[2015-12-01 21:21:25.020518] I [MSGID: 100030] [glusterfsd.c:2318:main] 0-/usr/sbin/glusterfs: Started running /usr/sbin/glusterfs version 3.7.6 (args: /usr/sbin/glusterfs --volfile-server=glusterfs.service.consul --volfile-id=/container-volumes /mnt/container-volumes)
[2015-12-01 21:21:25.046805] I [MSGID: 101190] [event-epoll.c:632:event_dispatch_epoll_worker] 0-epoll: Started thread with index 1
[2015-12-01 21:23:32.281829] E [socket.c:2278:socket_connect_finish] 0-glusterfs: connection to 159.203.111.205:24007 failed (Connection timed out)
[2015-12-01 21:23:32.281940] E [glusterfsd-mgmt.c:1818:mgmt_rpc_notify] 0-glusterfsd-mgmt: failed to connect with remote-host: glusterfs.service.consul (Transport endpoint is not connected)
[2015-12-01 21:23:32.281952] I [glusterfsd-mgmt.c:1824:mgmt_rpc_notify] 0-glusterfsd-mgmt: Exhausted all volfile servers
[2015-12-01 21:23:32.282211] W [glusterfsd.c:1236:cleanup_and_exit] (-->/lib64/libgfrpc.so.0(rpc_clnt_notify+0xd0) [0x7f971c408d50] -->/usr/sbin/glusterfs(+0xf6be) [0x7f971cb136be] -->/usr/sbin/glusterfs(cleanup_and_exit+0x69) [0x7f971cb0d6d9] ) 0-: received signum (1), shutting down
[2015-12-01 21:23:32.282257] I [fuse-bridge.c:5683:fini] 0-fuse: Unmounting '/mnt/container-volumes'.
```

Any ideas how we can improve the glusterfs install so that it can recover from failure?

**Comment by BrianHicks** [comment]
To follow up:

- on AWS, it looks like it tried to join once and failed. Probably because new peers can't probe into an existing cluster, they have to be probed from a current node. It's a security feature.
- on DO, @ryane established there was a network partition between the two hosts somehow. I'm doing another DO cluster to try and replicate this.

**Comment by BrianHicks** [comment]
This is all leading me to the conclusion that if one wants Gluster, one should add it separately. The playbooks need to be separate because Gluster's setup is fragile.

**Comment by BrianHicks** [comment]
- aad1dad separates Gluster into a separate "addons" playbook.
 - c531eaa fixes a race condition that can cause the behavior @ryane was seeing on DigitalOcean yesterday.

Any other feedback?

**Comment by stevendborrelli** [comment]
+1 on AWS

**Comment by BrianHicks** [comment]
Ok, the only thing left is restarts on the server nodes. There seems to be a bug regarding boot order in Gluster. I've asked on the mailing list, but it seems minor enough to me that we could ship this configuration. I've documented the bug in #892.

Other than that, are there any remaining issues?

**Comment by ryane** [comment]
It looks like the /mnt-container-volumes is still not mounted on client nodes after a restart (see #872).  After a client node reboots, the `GlusterFS volume mounted: container-volumes at /mnt/container-volumes` health check fails and:

```
$ sudo mount | grep gluster
[centos@ip-10-0-123-116 ~]$
```

Running `sudo mount -a` fixes the problem.

**Comment by BrianHicks** [comment]
@ryane can you make sure the boot options in fstab include `_netdev`? That should have fixed this issue. Unless the servers weren't up?

**Comment by ryane** [comment]
looks like it:

```
# cat /etc/fstab

#
# /etc/fstab
# Created by anaconda on Tue May 26 19:12:30 2015
#
# Accessible filesystems, by reference, are maintained under '/dev/disk'
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info
#
UUID=56480747-5a1d-4d9f-ba8c-11fbd530c3f0 / xfs     defaults,barrier=0 1 1
glusterfs.service.consul:/container-volumes /mnt/container-volumes glusterfs defaults,_netdev 0 0
```

**Comment by BrianHicks** [comment]
Boo! What platform is this? It worked when I tested on GCE.

**Comment by ryane** [comment]
my last test was on gce. I've seen it on aws too

**Comment by ryane** [comment]
Outside of the reboot issues (tracking in #872), this fixes a number of gluster issues and tested successfully on gce, aws, and digitial ocean.

**Pull request merged**
