### PR TITLE
Feature/remove registrator

### PR DESCRIPTION
**Pull request by ChrisAubuchon**
Remove registrator role

[Review on Reviewable](https://reviewable.io/reviews/ciscocloud/microservices-infrastructure/263)

### CODE REVIEW

**Comment by keithchambers** [comment]
How about we just use `zookeeper` for the service name vs `zookeeper-2888`, etc.

How about we add a check for ZK like `[[ "$(echo ruok | nc "$HOSTNAME" 2181 2>/dev/null)" == "imok" ]] && exit 0 || exit 1`

**Comment by ChrisAubuchon** [comment]
Currently the docker-zookeeper container uses the services as they would have been defined by registrator. It has three services: zookeeper, zookeeper-2888 and zookeeper-3888. This mimics the behavior of registrator until we update the zookeeper deployment.

**Comment by keithchambers** [comment]
Interesting.  So all our old deployments would break if we change the container.

We should take this as an opportunity to move the ZK code and container in to the CiscoCloud project / Docker Hub.

**Comment by ChrisAubuchon** [comment]
And I think we should avoid using the `latest` tag in the containers.

**Comment by keithchambers** [comment]
Add move to pulling in explicitly tagged version?  If that's what you mean I 100% agree.

**Comment by ChrisAubuchon** [comment]
That's what I was thinking. 0.1, 0.2, etc.

**Comment by ChrisAubuchon** [comment]
Do we have a CiscoCloud Docker Hub? There are several containers we can move there

**Comment by keithchambers** [comment]
@ChrisAubuchon I'm getting the following.  In meetings, meetings, meetings -- I haven't had a chance to debug.

```
PLAY [dc1:&zookeeper_servers] ************************************************* 

TASK: [zookeeper | generate default env file] ********************************* 
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ******************************************************************** 
upgrade all packages -------------------------------------------------- 224.90s
upgrade kernel package ------------------------------------------------- 87.22s
wait for host boot ----------------------------------------------------- 67.70s
nova_compute  ---------------------------------------------------------- 55.67s
dnsmasq | install packages --------------------------------------------- 40.57s
registrator | reload registrator --------------------------------------- 37.28s
consul | enable nginx-consul ------------------------------------------- 36.56s
docker | install docker ------------------------------------------------ 31.33s
common | configure hosts file ------------------------------------------ 29.06s
docker | install latest device-mapper-libs ----------------------------- 19.94s
           to retry, use: --limit @/Users/kechambe/site.retry

host-01                    : ok=59   changed=44   unreachable=0    failed=1   
host-02                    : ok=59   changed=44   unreachable=0    failed=1   
host-03                    : ok=59   changed=44   unreachable=0    failed=1   
host-04                    : ok=58   changed=43   unreachable=0    failed=1   
host-05                    : ok=58   changed=43   unreachable=0    failed=1   
host-06                    : ok=87   changed=60   unreachable=0    failed=0   
host-07                    : ok=87   changed=60   unreachable=0    failed=0   
host-08                    : ok=87   changed=60   unreachable=0    failed=0   
host-09                    : ok=65   changed=50   unreachable=0    failed=0   
host-10                    : ok=65   changed=50   unreachable=0    failed=0   
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Pull request merged**
