### PR TITLE
Marathon conf permissions

### PR DESCRIPTION
**Pull request by sehqlr**
This recursively sets /etc/marathon/conf permissions to 700. 
I had to add some reverts to this, because I based this branch on a different pull request instead of master :frowning:

### CODE REVIEW

**Comment by siddharthist** [comment]
This breaks a few Distributive health checks for marathon that check the existence of several configuration files under that directory. We should modify them and merge a new version of distributive-rpm at the same time as this PR.

**Comment by stevendborrelli** [comment]
My concern is that apps in '/etc/marathon` contain sensitive information. Maybe we should move the apps to a separate directory and make it 700.

**Comment by sehqlr** [comment]
IIRC, you were talking about having that separate dir for apps be `/etc/marathon/apps`? Do we need to make `/etc/marathon` mode 700, and then `/etc/marathon/apps` be something like 744?

**Comment by stevendborrelli** [comment]
`/etc/marathon/apps`, `/etc/marathon/store`, `/etc/marathon/conf` should be 700, since there are credentials in some of the files.

**Comment by sehqlr** [comment]
I've added the mode change to `/etc/marathon/store`, and added an entry for `/etc/marathon/apps`. Is there anything in the marathon role that should be migrated to the apps directory, or is that all user configured?

**Comment by ryane** [comment]
take a look at the jobs.yml file in the marathon role. we probably want to move the marathon-consul and mesos-consul json files into the `/etc/marathon/apps` directory

**Comment by ryane** [comment]
I am seeing the broken distributive checks:

```
time="2015-11-17T16:32:24Z" level=warning msg="Check(s) failed, printing checklist report" checklist="marathon health check" report="↴\nTotal: 16\nPassed: 10\nFailed: 6\nInsufficient permissions to read: /etc/marathon/conf/\nInsufficient permissions to read: /etc/marathon/conf/zk\nInsufficient permissions to read: /etc/marathon/conf/http_port\nInsufficient permissions to read: /etc/marathon/conf/event_subscriber\nInsufficient permissions to read: /etc/marathon/conf/hostname\nInsufficient permissions to read: /etc/marathon/marathon.nginx"
```

**Comment by sehqlr** [comment]
What user is being used for the checks? The permissions for the conf dir is 700

**Comment by BrianHicks** [comment]
Just a note: none of these files are executable, so this should probably `600` instead of `700`, as well.

**Comment by sehqlr** [comment]
@BrianHicks How does this look?

**Comment by BrianHicks** [comment]
@sehqlr looks good WRT the permission, thanks.

**Comment by ryane** [comment]
we still need a solution for the failing distributive checks

**Comment by sehqlr** [comment]
Right. We were talking about that on Slack, but I don't think we came to a decision about what to do one way or another

**Comment by siddharthist** [comment]
@sehqlr One solution is just to remove them from distributive-rpm and make a new release.

**Comment by ryane** [comment]
do we need to push this to the next release?

**Comment by stevendborrelli** [comment]
If we can't get this resolved fist thing in the morning, it will have to go to 0.6.

**Comment by siddharthist** [comment]
This will be ready once we have a new distributive-rpm release after merging https://github.com/CiscoCloud/distributive-rpm/pull/27.

**Comment by BrianHicks** [comment]
Merge order note: we need to either apply only one of this and #955, or apply this one first.

**Comment by siddharthist** [comment]
Second merge order note: this has to be after #959.

**Comment by BrianHicks** [comment]
#955 got merged, @sehqlr could you check if this is still relevant?

**Comment by ryane** [comment]
@sehqlr @BrianHicks @siddharthist so what's the plan for this one? merge #959, rebase this to be compatible with the changes in #955, and then merge?

**Comment by sehqlr** [comment]
I will check to see if this is still relevant, first.

**Comment by BrianHicks** [comment]
It's obsoleted by #955, as far as I can tell. We don't need to change permissions on the folder because it doesn't exist anymore.

**Comment by ryane** [comment]
But the files containing sensitive information just moved to /etc/marathon so that directory should have the more restrictive permissions, right?

**Comment by BrianHicks** [comment]
That's a good point. Yes, it should.

**Comment by ryane** [comment]
While the change in #1034 is good, it doesn't actually address the entire problem in this issue. There are still files in `/etc/marathon/*` that contain sensitive information (tokens/secrets). I created a new issue to track this: #1047

**Pull request closed without merging**
