### PR TITLE
Install Distributive as part of the common role

### PR DESCRIPTION
**Pull request by siddharthist**
Includes a health check for Consul, which runs on provisioning for a sanity check, and registers to be run every 10 minutes.

[Distributive](https://github.com/CiscoCloud/distributive) is the tool we will be using to check the health of our nodes via Consul. It is configured via JSON files (checklists). Eventually, each Ansible role will have its own checklist.

### CODE REVIEW

**Comment by stevendborrelli** [comment]
This looks awesome. We're going to include this in a post 0.3 release, as we are feature freezing right now.

**Comment by siddharthist** [comment]
Tested and working on Vagrant, deploying to Openstack now.

**Comment by siddharthist** [comment]
Tested and working on Vagrant.

**Comment by stevendborrelli** [comment]
@siddharthist there have been a lot of changes in distributive, does this install the newest RPM?

**Comment by siddharthist** [comment]
@stevendborrelli I will be updating the RPM version and testing today.

**Comment by siddharthist** [comment]
Updated, tested yet again on Vagrant and Openstack.

**Comment by stevendborrelli** [comment]
@siddharthist Issues I am seeing on digital ocean: 

1. This needs to be updated to fix a merge conflict
2. Getting this error: 
```
Creating checklist...
2015/06/15 21:15:57 Couldn't read file:
	Path: /usr/share/distributive/consul.json
	Error: open /usr/share/distributive/consul.json: permission denied
```

**Comment by stevendborrelli** [comment]
On a new vagrant install, showing critical. It seems to be configured ok. 

Also, `distributive-service-consul` should probably be renamed to something like consul-config.

**Comment by siddharthist** [comment]
All the above suggestions are in that most recent commit.

**Comment by siddharthist** [comment]
All the above suggestions are in that most recent commit.

**Comment by siddharthist** [comment]
Most recent commit tested and working on Vagrant and DO.

**Pull request merged**
