### PR TITLE
Fix logrotate role to use files instead of templates

### PR DESCRIPTION
**Pull request by keithchambers**

### CODE REVIEW

**Comment by ChrisAubuchon** [comment]
The logrotate role is not in vagrant.yml. Is there a reason not to have it in Vagrant?

**Comment by keithchambers** [comment]
That's probably a oversight.  Let me add it now.

**Comment by keithchambers** [comment]
durp

**Comment by ChrisAubuchon** [comment]
The mesos logrotate file is broken too. It's rotating `/var/log/mesos/*`. That will rotate already rotated logs. There would need to be an `olddir` directive to move the rotated logs out.

Also the mode in the copy needs to be `0644` instead of `644`.

**Pull request merged**
