### PR TITLE
Marathon port should be configurable

### PR DESCRIPTION
**Pull request by ludovicc**
Small omission

### CODE REVIEW

**Comment by eirslett** [comment]
If you search the whole project for "18080", you'll see that the value is hardcoded in lots of places. So in order to make this work, the variable would have to be used there as well.

**Comment by stevendborrelli** [comment]
@ludovicc we'll need the other references to this port updated before we can merge this branch.

**Comment by siddharthist** [comment]
@ludovicc Are you still working on this? Or should we close this PR?

**Comment by siddharthist** [comment]
Since there hasn't been further work or interest in this PR, I'm going to close it. If anybody wants to continue to make progress on this, please reopen (and/or open an issue)!

**Pull request closed without merging**
