### PR TITLE
Fix/root ulimit

### PR DESCRIPTION
**Pull request by sehqlr**
This was supposed to be resolved with #780, but it seems that the ulimit was not being set for root users based on `limit.conf`. Because these limits are defined by login, I added the ulimit fix as a command in `/root/.bashrc`. I would like @stevendborrelli to confirm that this version of the fix works as expected.

### CODE REVIEW

**Comment by stevendborrelli** [comment]
The more I think about it, we should just update the consul.service to have 65k files. See the etcd.service example below for LimitNOFILE: 

```
[Service]
Type=simple
WorkingDirectory=/var/lib/etcd/
EnvironmentFile=-/etc/etcd/etcd.conf
User=etcd
# set GOMAXPROCS to number of processors
ExecStart=/bin/bash -c "GOMAXPROCS=$(nproc) /usr/bin/etcd"
Restart=on-failure
LimitNOFILE=65536
```

**Comment by sehqlr** [comment]
So, with the limit increased for consul, that will none of the other services that consul uses will run out of files, right? Also, I forgot to mention in my commit that I made the system's max-file equal to 65536, to make it a power of two, like in the etcd example you gave me.

**Comment by stevendborrelli** [comment]
@sehqlr There are a couple of ways of modifying the consul.service file that I think will be preferable to modifying a .service file that is installed via rpm: 

1. Upgrade the consul-rpm upstream
or 
2. Create a local override file in `/etc/systemd/system/consul.service.d`.

Since we create the consul package, we should update the RPM and increment the version. I think @ChrisAubuchon can assist in showing you where the package is.

**Comment by sehqlr** [comment]
I wanted to make a note that this PR could be closed without merging if this gets merged: ciscocloud/consul-rpm#1

**Comment by BrianHicks** [comment]
I'm going to go ahead and close this since CiscoCloud/consul-rpm#1 was merged. If that's incorrect, please reopen.

**Pull request closed without merging**
