### PR TITLE
Make overlay the default docker storage backend

### LINKED ISSUE #903: Docker Overlay FS support
With the release of Redhat 7.2, we should give overlayfs another try and see if the bugs have been worked out. 

This would involve at least updating `/etc/sysconfig/docker-storage` to have a `STORAGE_DRIVER=overlay`.

### PR DESCRIPTION
**Pull request by stevendborrelli**
Make overlayfs the default. Requires Centos 7 1511.

Fixes #903.

### CODE REVIEW

**Comment by TanyaCouture** [comment]
Successfully deployed with:
Vagrant
AWS

**Comment by ryane** [comment]
@stevendborrelli this is waiting on an upgrade script, correct?

**Comment by stevendborrelli** [comment]
Yes, I've asked @avnik to get the upgrade together.

**Comment by avnik** [comment]
@ryane @stevendborrelli I work on smooth upgrade solution

**Comment by TanyaCouture** [comment]
Installed and checks passed on:
Openstack

**Comment by stevendborrelli** [comment]
@TanyaCouture what was tested and what were the results?

**Comment by TanyaCouture** [comment]
@stevendborrelli Edited comment above.

**Comment by ryane** [comment]
was an upgrade from 0.5.1 tested?

**Comment by TanyaCouture** [comment]
@ryane It hasn't but I'll install on 0.5.1 and upgrade from there.

**Comment by TanyaCouture** [comment]
Tests for upgrade from 0.5.1 on Openstack passed:

Steps taken:
     checkout 0.5.1
      terraform apply
      ansible-playbook -e 'serial=0' playbooks/upgrade-packages.yml
      ansible-playbook -e @security.yml terraform.yml
      ran sudo docker info, output as follows:
	Containers: 4
	Images: 8
	Storage Driver: devicemapper
 	Pool Name: docker-253:1-1055939-pool
 	Pool Blocksize: 65.54 kB
 	Backing Filesystem: extfs
 	Data file: /dev/loop0
 	Metadata file: /dev/loop1
 	Data Space Used: 1.601 GB
 	Data Space Total: 107.4 GB
 	Data Space Available: 43.14 GB
 	Metadata Space Used: 1.753 MB
 	Metadata Space Total: 2.147 GB
 	Metadata Space Available: 2.146 GB
 	Udev Sync Supported: true
 	Deferred Removal Enabled: false
 	Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 	Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 	Library Version: 1.02.93-RHEL7 (2015-01-28)
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 3.10.0-229.14.1.el7.x86_64
	Operating System: CentOS Linux 7 (Core)
	CPUs: 2
	Total Memory: 3.86 GiB
	Name: jump-tx3.cisco.com
	ID: ELQL:I4G6:CLQ7:775F:DJUH:6H7Z:CTCF:VMBZ:BAW6:5PTO:D6KB:W5U5
      ran 2 docker containers:
	Existence of both containers verified with sudo docker ps -l

	sudo docker run ubuntu:14.04 /bin/echo 'Hello world’:  		output: Hello World
	sudo docker run -d -P training/webapp python app.py
		output verified with its port, 32768: curl localhost:32768
			output: Hello World! 	

    checkout feature/overlays
      ansible-playbook -e @security.yml terraform.yml
      ran sudo docker info, output was as follows:
	Containers: 7
	Images: 25
	Storage Driver: devicemapper
 	Pool Name: docker-253:1-1055939-pool
	 Pool Blocksize: 65.54 kB
 	Backing Filesystem: extfs
	 Data file: /dev/loop0
 	Metadata file: /dev/loop1
 	Data Space Used: 2.272 GB
 	Data Space Total: 107.4 GB
 	Data Space Available: 42.46 GB
 	Metadata Space Used: 2.671 MB
 	Metadata Space Total: 2.147 GB
 	Metadata Space Available: 2.145 GB
	Udev Sync Supported: true
 	Deferred Removal Enabled: false
 	Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 	Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 	Library Version: 1.02.93-RHEL7 (2015-01-28)
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 3.10.0-229.14.1.el7.x86_64
	Operating System: CentOS Linux 7 (Core)
	CPUs: 2
	Total Memory: 3.86 GiB
	Name: jump-tx3.cisco.com
	ID: ELQL:I4G6:CLQ7:775F:DJUH:6H7Z:CTCF:VMBZ:BAW6:5PTO:D6KB:W5U5
      run some docker containers
	Existence of both containers verified with sudo docker ps -l

	sudo docker run ubuntu:14.04 /bin/echo 'Hello world’:  		output: Hello World
	sudo docker run -d -P training/webapp python app.py
		output verified with its port, 32769: curl localhost:32769
			output: Hello World!

**Comment by TanyaCouture** [comment]
Clean install on Openstack test passed: 
Steps taken:
     checkout master branch
      terraform apply
      ansible-playbook -e 'serial=0' playbooks/upgrade-packages.yml
      ansible-playbook -i plugins/inventory/terraform.py -e @security.yml terraform.sample.yml
     ran sudo docker info, output as follows:

           Containers: 9
           Images: 25
           Storage Driver: device mapper
           Pool Name: docker-253:1-1055939-pool
           Pool Blocksize: 65.54 kB
           Backing Filesystem: extfs
           Data file: /dev/loop0
           Metadata file: /dev/loop1
           Data Space Used: 2.276 GB
           Data Space Total: 107.4 GB
           Data Space Available: 42.46 GB
           Metadata Space Used: 2.765 MB
           Metadata Space Total: 2.147 GB
           Metadata Space Available: 2.145 GB
           Udev Sync Supported: true
          Deferred Removal Enabled: false
          Data loop file: /var/lib/docker/devicemapper/devicemapper/data
          Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
          Library Version: 1.02.93-RHEL7 (2015-01-28)
          Execution Driver: native-0.2
          Logging Driver: json-file
          Kernel Version: 3.10.0-229.14.1.el7.x86_64
          Operating System: CentOS Linux 7 (Core)
          CPUs: 2
          Total Memory: 3.86 GiB
          Name: jump-tx3.cisco.com
          ID: ELQL:I4G6:CLQ7:775F:DJUH:6H7Z:CTCF:VMBZ:BAW6:5PTO:D6KB:W5U5

ran 2 docker containers:
	Existence of both containers verified with sudo docker ps -l

	sudo docker run ubuntu:14.04 /bin/echo 'Hello world’  		
                output: Hello World
	sudo docker run -d -P training/webapp python app.py
		output verified with its port, 32770: curl localhost:32770
			output: Hello World! 
 
checkout feature/overlayfs
      ansible-playbook -i plugins/inventory/terraform.py -e @security.yml terraform.sample.yml
      ran sudo docker info, output was as follows:

           Containers: 11
           Images: 25
           Storage Driver: devicemapper
           Pool Name: docker-253:1-1055939-pool
           Pool Blocksize: 65.54 kB
           Backing Filesystem: extfs
           Data file: /dev/loop0
           Metadata file: /dev/loop1
           Data Space Used: 2.28 GB
           Data Space Total: 107.4 GB
           Data Space Available: 42.45 GB
           Metadata Space Used: 2.859 MB
           Metadata Space Total: 2.147 GB
           Metadata Space Available: 2.145 GB
           Udev Sync Supported: true
           Deferred Removal Enabled: false
           Data loop file: /var/lib/docker/devicemapper/devicemapper/data
           Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
           Library Version: 1.02.93-RHEL7 (2015-01-28)
           Execution Driver: native-0.2
           Logging Driver: json-file
           Kernel Version: 3.10.0-229.14.1.el7.x86_64 
           Operating System: CentOS Linux 7 (Core)
           CPUs: 2
           Total Memory: 3.86 GiB
           Name: jump-tx3.cisco.com
           ID: ELQL:I4G6:CLQ7:775F:DJUH:6H7Z:CTCF:VMBZ:BAW6:5PTO:D6KB:W5U5

      run  2 docker containers
	Existence of both containers verified with sudo docker ps -l

	sudo docker run ubuntu:14.04 /bin/echo 'Hello world’ 		output: Hello World
	sudo docker run -d -P training/webapp python app.py
		output verified with its port, 32772: curl localhost:32772
			output: Hello World!

**Comment by siddharthist** [comment]
Thanks for great testing and logging @TanyaCouture!

**Comment by avnik** [comment]
On Mon, Jan 11, 2016 at 03:27:42PM -0800, Tanya Couture wrote:

> checkout feature/overlayfs
>       ansible-playbook -i plugins/inventory/terraform.py -e @security.yml terraform.sample.yml
>       ran sudo docker info, output was as follows:
> 
>            Containers: 11
>            Images: 25
>            Storage Driver: devicemapper

Looks not good.
Clean install of feature/overlayfs (w/o master first should
expose `Storage Driver: overlayfs`.

Will check again today.

**Pull request merged**
