### PR TITLE
Consul: update to 0.6.0

### LINKED ISSUE #825: Replace consul-rpm with hammer-built package
We are currently using: https://github.com/CiscoCloud/consul-rpm to build the consul and consul-ui rpms.

As part of our CI workflow, migrate to using the package built at https://github.com/asteris-llc/consul-packaging

### PR DESCRIPTION
**Pull request by BrianHicks**
Updates Consul to 0.6.0 and consolidates the number of tasks performed in the role.

Tested on DO.

Closes #825 as well.

### CODE REVIEW

**Comment by ryane** [comment]
I think we need an upgrade path for existing clusters. Currently getting this error:

```
file /usr/bin/consul-cli from install of consul-cli-0.1.0-1.x86_64 conflicts with file from package consul-utils-0.1.0-1.el7.centos.x86_64
```

**Comment by ryane** [comment]
Looks like we also have to update the vagrant image:

```
==> default:   file /usr/bin/consul-cli from install of consul-cli-0.1.0-1.x86_64 conflicts with file from package consul-utils-0.1.0-1.el7.centos.x86_64
==> default:   file /etc/consul/consul-ui.json from install of consul-0.6.0-1.x86_64 conflicts with file from package consul-ui-0.5.2-3.el7.centos.x86_64
==> default:   file /usr/share/consul-ui from install of consul-0.6.0-1.x86_64 conflicts with file from package consul-ui-0.5.2-3.el7.centos.x86_64
==> default:   file /usr/share/consul-ui/index.html from install of consul-0.6.0-1.x86_64 conflicts with file from package consul-ui-0.5.2-3.el7.centos.x86_64
==> default:   file /usr/share/consul-ui/static from install of consul-0.6.0-1.x86_64 conflicts with file from package consul-ui-0.5.2-3.el7.centos.x86_64
==> default:   file /usr/share/consul-ui/static/application.min.js from install of consul-0.6.0-1.x86_64 conflicts with file from package consul-ui-0.5.2-3.el7.centos.x86_64
==> default:   file /usr/share/consul-ui/static/base.css from install of consul-0.6.0-1.x86_64 conflicts with file from package consul-ui-0.5.2-3.el7.centos.x86_64
==> default:   file /usr/share/consul-ui/static/base.css.map from install of consul-0.6.0-1.x86_64 conflicts with file from package consul-ui-0.5.2-3.el7.centos.x86_64
==> default:   file /usr/share/consul-ui/static/bootstrap.min.css from install of consul-0.6.0-1.x86_64 conflicts with file from package consul-ui-0.5.2-3.el7.centos.x86_64
==> default:   file /usr/share/consul-ui/static/consul-logo.png from install of consul-0.6.0-1.x86_64 conflicts with file from package consul-ui-0.5.2-3.el7.centos.x86_64
==> default:   file /usr/share/consul-ui/static/favicon.png from install of consul-0.6.0-1.x86_64 conflicts with file from package consul-ui-0.5.2-3.el7.centos.x86_64
==> default:   file /usr/share/consul-ui/static/loading-cylon-purple.svg from install of consul-0.6.0-1.x86_64 conflicts with file from package consul-ui-0.5.2-3.el7.centos.x86_64
```

**Comment by BrianHicks** [comment]
I think I've got a fix in 07368d5. See the diff in the package at https://github.com/asteris-llc/mantl-packaging/compare/e31517321fc03b24729c2e7cbcb1dc241e36276c...dfc5389

**Comment by ChrisAubuchon** [comment]
I've incorporated this into PR https://github.com/CiscoCloud/microservices-infrastructure/pull/603 because of the issues we have with consul 0.5.2 failing during deployment. We can use that PR instead of having to rebase this one if we like.

**Comment by BrianHicks** [comment]
@ChrisAubuchon let's just go ahead and tie it to #603. That sounds fine.

**Comment by acsrujan** [comment]
So, 'feature/consul-0.6.0' branch can be deleted.

**Pull request closed without merging**
