### PR TITLE
added requirement of python 2 plus no-parallel

### LINKED ISSUE #509: documentation fixes
After talking with @Raffo on Gitter, I think we need some updates to the docs:

- [ ] make it clear that Python 2 is the version one should use for this project
- [ ] make it clearer that `vagrant up` is the only command one needs to get started

### PR DESCRIPTION
**Pull request by ObjectiveJoe**
addresses documentation fixes #509

### CODE REVIEW

**Comment by stevendborrelli** [comment]
Thanks for the pull request! 

Do you think the wording might be a bit confusing? I thought that Python 3 didn't work, and this update implies that it does. 

cc @BrianHicks

**Comment by BrianHicks** [comment]
Yeah, it should just require 2.7. 3 doesn't work.

**Comment by kenjones-cisco** [comment]
Might be worth noting that the python 2.7 due to dependency on ansible. Otherwise nothing within this project should prevent python 3.x users if ansible were to support python 3.x

**Comment by BrianHicks** [comment]
There's also a bug in terraform.py that prevents it from being run
successfully on 3. Since we're 2.7 only for now because of Ansible it's
probably not worth our time to fix, for now.

Leaving it as simply requiring 2.7 in the docs is simpler, in any case, and
we should strive for simplicity.

**Comment by BrianHicks** [comment]
@ObjectiveJoe apart from the fixes mentioned above, this looks good. As soon as you can get it in we'll merge it. Thanks! :)

**Comment by ObjectiveJoe** [comment]
I changed documentation to simple say requires Python 2.7; didn't mention
that it was because of current Ansible version. Submitted change; should be
available in current pull request.

**Comment by BrianHicks** [comment]
@ObjectiveJoe merged, thanks!

**Pull request merged**
