### PR TITLE
Collect licenses on mantl components

### PR DESCRIPTION
**Pull request by TanyaCouture**
license documentation for micro services-infrastructure

### CODE REVIEW

**Comment by stevendborrelli** [comment]
Some feedback.

1. Can this be formatted into the same .rst format as the rest of our documentation? This should be a section in our documentation. 

2. This misses the licenses of a lot of the tools we install that are not part of Centos, here is a sampling:
- consul
- vault
- zookeeper
- mesos
- kubernetes
- mesos-consul
- consul-cli
- chronos
- marathon
- mesos-ui
- mantl-api

**Comment by TanyaCouture** [comment]
closer to completion now

**Comment by TanyaCouture** [comment]
changing formatting

**Comment by ohal** [comment]
since we have CI jenkins host which is tied up with PR's and commits and continuously building the MANTL here http://173.39.246.217/view/CCS-MI-US-INTERNAL-1-QA-1/
I think it will be better to make all changes as one or several commits and then make the PR so we can avoid building/testing 25 clusters in a row
but it's just my opinion )

**Comment by corebug** [comment]
Is it **absolutely necessary** to commit **every file**?

**Comment by corebug** [comment]
@TanyaCouture I can merge all this stuff into one commit and recreate a PR, would you like me to?

**Comment by sehqlr** [comment]
@TanyaCouture was just showing this to me. She didn't know that all of these changes were triggering Jenkins each time. Is there anyway for her to signal to Jenkins not to build?

**Comment by TanyaCouture** [comment]
@corebug I'm finished now, there won't be more commits.

**Comment by ohal** [comment]
@jenkins skip ci

**Comment by sehqlr** [comment]
@ohal OK, great, thanks!

**Comment by benschumacher** [comment]
Does our Jenkins integration support "CI SKIP" ??

**Comment by benschumacher** [comment]
Just want to clarify a bit what's in the document. It seems we have a mix of tools used to help "build" the system, as well as tools that are part of the execution environment, correct?

For example, I noticed that Packer is listed here, but I don't imagine we're placing this on our deployed VMs. Is there any shot we can further organize this list around this principal? I'm particularly interested in seeing a specific list of software components installed onto a running instance of Mantl as a Mesos+Marathon+Chronous+Consul+Traefik solution.

Thanks,
Ben

**Comment by ohal** [comment]
@benschumacher 
> Does our Jenkins integration support "CI SKIP" ??

seems not yet supported

**Comment by TanyaCouture** [comment]
@benschumacher, there's a proposal to automate license documentation. If you would like to contribute to it, here's a link:
https://gist.github.com/sehqlr/faa63c83c2eb2af3f8e8

**Comment by TanyaCouture** [comment]
replaced by #1006

**Pull request closed without merging**
