### PR TITLE
Remove NetworkManager from Vagrant box

### PR DESCRIPTION
**Pull request by michaeltchapman**
NetworkManager is problematic in Vagrant environments since it will
tear down hostonly private networks as soon as they are created by
the vagrant provisioner. This patch removes it as it's included in
@core by default.

Partially addresses #256 #503

### CODE REVIEW

**Comment by stevendborrelli** [comment]
Thanks! We'll try to get this merged today.

**Comment by stevendborrelli** [comment]
@michaeltchapman in my testing on this, it seems that the local consul UI at http://localhost:8500 is broken. 

Can you check if you are getting the UI to come up?

**Comment by michaeltchapman** [comment]
Double checking consul comes up now - I only checked marathon + mesos. I was actually not testing this on its own, but in conjunction with a private network patch, which puts consul at https://192.168.242.55:8500 since the forwarded ports are gone. I'll add a second commit for that so you can test, but I think @altvnk was looking at a yaml based node description which would be more appropriate for bringing up a cluster, which is the end goal. The best option is probably to merge both at once, so I'll leave this here for @altvnk to cherry-pick from.

**Comment by stevendborrelli** [comment]
That sounds great. I'd love to remove the port forwarding.

**Comment by michaeltchapman** [comment]
for anyone who wants to test:

    cd img-build/packer
    packer build -only=aio-vagrant-virtualbox all-in-one.json
    vagrant box add mi-testing microservices-infrastructure-vbox.box
    cd ../..

then replace the box line in the `Vagrantfile`:

    config.vm.box = "mi-testing"

**Comment by stevendborrelli** [comment]
This also affects our AWS AMI build. We're going to need to push this to 0.4.0.

**Comment by matjohn2** [comment]
Removing this entirely from packer also removes needed components for GCE/AWS support. This will require re-working to not affect public cloud installations. Planning then Deployment (feel free to break into smaller issues for this sprint)

**Comment by ryane** [comment]
fyi, vagrant 1.7.3 (released July 10) fixes the issue where NM tears down private networks.

https://github.com/mitchellh/vagrant/pull/5709

**Comment by BrianHicks** [comment]
@michaeltchapman thanks for the contribution, it kicked off our re-examining how the Vagrant process works. #612 and #617 should do the same things with our new format, so I'm going to close this now. Thanks again!

**Pull request closed without merging**
