### PR TITLE
Move aws terraform to smaller modules and support multi-az deployments

### PR DESCRIPTION
**Pull request by anners**
This breaks up the aws-dc module into smaller modules: (similar to https://github.com/CiscoCloud/microservices-infrastructure/pull/901)
aws/ssh
aws/vpc
aws/nodes/control
aws/nodes/edge
awsnodes/worker
The elb and route53 modules are now under aws/ to be consistent. 

aws.sample.tf also reflects these changes and also includes examples of using remote state for VPC variables. 

The AWS doucumentation has been updated to reflect all the changes as well.

Mult-AZ support has been added addressing #890

### CODE REVIEW

**Comment by TanyaCouture** [comment]
Am testing this PR by deploying it on AWS. After "terraform apply", this is the error on all nodes:

```* aws_route53_record.dns-worker.1: NoSuchHostedZone: No hosted zone found with ID: XXXXXXXXXXXX
	status code: 404, request id: #########```

Am I missing a modification for successful deployment?

**Comment by anners** [comment]
You need to replace XXXXXX with your hosted zone id.

**Comment by TanyaCouture** [comment]
@anners Would you be able to review this PR? We don't have a hosted zone id, and apparently we don't usually test the DNS part of this type of PR. Thanks.

**Comment by anners** [comment]
@TanyaCouture I was able to successfully run terraform apply, lmk if you want me to do anything thing else. 

module.route53.aws_route53_record.dns-control.1: Creation complete
module.route53.aws_route53_record.dns-control.2: Creation complete
module.route53.aws_route53_record.dns-control-group.1: Creation complete
module.route53.aws_route53_record.dns-control.0: Creation complete
module.route53.aws_route53_record.dns-control-group.0: Creation complete
module.route53.aws_route53_record.dns-control-group.2: Creation complete
module.route53.aws_route53_record.elb-cname: Creation complete

Apply complete! Resources: 51 added, 0 changed, 0 destroyed.

**Comment by TanyaCouture** [comment]
@anners Looks good to me. Thank you!

**Comment by anners** [comment]
I think this branch should be good to go. I added back the original aws.tf file for backwards compatibility.

**Comment by siddharthist** [comment]
@anners This looks like it has some merge conflicts, unfortunately :(

**Comment by anners** [comment]
sorry about that. This branch is drifting too much. Hopefully I fixed this
time.

On Mon, Jan 25, 2016 at 10:58 AM, Langston Barrett <notifications@github.com

**Pull request merged**
