### PR TITLE
terraform inventory - use public ip if not private

### PR DESCRIPTION
**Pull request by fernandezvara**
Issue #757

### CODE REVIEW

**Comment by eirslett** [comment]
That stuff actually breaks mantl as it is today:disappointed:
It only supports single-network stacks.
The terraform.py stuff actually hardcodes the public IP and pretends it's a private IP.
Hopefully it will be supported better in the future... since DigitalOcean lets you have internal traffic for free, while you pay for "public" traffic.

**Comment by stevendborrelli** [comment]
What are the changes we need to make in order to support multiple networks?

**Comment by ChrisAubuchon** [comment]
For starters:
1. Add a third network variable (`nat_ip4`) for AWS and GCE.
2. Mesos and Marathon would change to binding on `private_ip4` instead of on a different port on `public_ip4`. Other apps as well
3. The nginx proxies would listen on `public_ip4` and proxy to `private_ip4:<port>`

**Comment by eirslett** [comment]
Why is 1. needed? Does AWS and GCE already have two IP addresses, both public? :confused: 
2 and 3 are definitely needed.
First of all, terraform.py must be changed across *all* the cloud providers, so that it actually delivers both a public and a private IP address. Private networking must be made a requirement on DigitalOcean, but I don't think that's a problem any longer, I think they've released private networking in all their data centers by now.
The Vagrant stuff must also be updated to use both IPs. That's maybe the first step, since Vagrant is easier to use for testing.

**Comment by ChrisAubuchon** [comment]
AWS and GCE each have one IP address on the host and a NAT IP address that is not on the host. They are single network systems with an external address. The `nat_ip4` variable would be used as the advertised address for, at least, consul in a multi-dc configuration. So for AWS and GCE, `public_ip4 == private_ipv4`. DO would have `private_ip4` and `public_ip4 == nat_ip4`

**Comment by siddharthist** [comment]
Since this isn't the repo for terraform.py, I'm going to close this PR. Let's continue the discussion in #757!

**Pull request closed without merging**
