### PR TITLE
Collectd plugins for Mesos, Marathon, Docker and Zookeeper.

### PR DESCRIPTION
**Pull request by corebug**
This is a cumulative PR that incorporates (refactored and rebased to current master.):

* collectd base: https://github.com/CiscoCloud/microservices-infrastructure/pull/335
* Docker: https://github.com/CiscoCloud/microservices-infrastructure/pull/352
* Mesos: https://github.com/CiscoCloud/microservices-infrastructure/pull/347
* Marathon: https://github.com/CiscoCloud/microservices-infrastructure/pull/345
* ZooKeeper: https://github.com/CiscoCloud/microservices-infrastructure/pull/346

### CODE REVIEW

**Comment by corebug** [comment]
@stevendborrelli here you are, please merge it.

**Comment by stevendborrelli** [comment]
@corebug thanks! @ryane is going to be testing an merging this.

**Comment by corebug** [comment]
@ryane @stevendborrelli just fixed the conflicts, please merge it.

**Comment by ryane** [comment]
I fixed one syntax error in the marathon playbook but, otherwise, this seems to be ok. I can see the collectd metrics flowing into logstash from each of the plugins

**Pull request merged**
