### PR TITLE
Revert back to previous `consul-rolling-restart.sh`

### PR DESCRIPTION
**Pull request by ChrisAubuchon**
The updated version does not work when run on a subset of servers.
Issue https://github.com/CiscoCloud/microservices-infrastructure/issues/1068

### CODE REVIEW

**Comment by ryane** [comment]
fresh gce build stuck on the `restart consul` task:

```
NOTIFIED: [consul | restart consul] *******************************************
changed: [resching-gce-worker-003]
changed: [resching-gce-worker-002]
changed: [resching-gce-worker-001]
changed: [resching-gce-edge-01]
# stuck here for about 15 minutes so far
```

@ChrisAubuchon any idea? does this PR depend on the updated consul-cli (#1079)?

**Comment by ChrisAubuchon** [comment]
Ack! Meant to update to the latest consul-cli in this branch.

**Comment by ChrisAubuchon** [comment]
This branch has the update consul-cli now

**Comment by ryane** [comment]
successful gce build.

I then increased the count of worker nodes (from 3 to 5) and ran the following:

```shell
terraform apply
ansible-playbook -e 'serial=0' playbooks/upgrade-packages.yml -l resching-gce-worker-004,resching-gce-worker-005
ansible-playbook -e @security.yml terraform.yml -l resching-gce-worker-004,resching-gce-worker-005
```

Consul restart completed successfully, no other errors during the build, and cluster is all green. @ChrisAubuchon any other scenario that should be tested?

**Comment by ryane** [comment]
also should we just close #1079 since it is included here?

**Comment by ChrisAubuchon** [comment]
Maybe add a control node. Shouldn't make any difference though.

We can close #1079

**Comment by ryane** [comment]
lgtm

**Comment by ohal** [comment]
looks like it fixes also this https://github.com/CiscoCloud/microservices-infrastructure/issues/1077
tested here on the openstack [663](http://173.39.245.19/view/CCS-MI-US-INTERNAL-1-QA-1/job/PR-to-master-CCS-MI-US-INTERNAL-1-QA-1/663/robot/report/log.html)

**Pull request merged**
