### PR TITLE
Unify notation for file system permissions

### PR DESCRIPTION
**Pull request by loshkovskyi**
Fix issue #943. Start using full numeric notation in all playbooks.

### CODE REVIEW

**Comment by eirslett** [comment]
Let's add ansible-lint to the project, with a special rule that ensures file permissions are always notated that way?
(Otherwise somebody will forget)

**Comment by stevendborrelli** [comment]
@eirslett good idea! Looping in @sehqlr to see how we can add ansible-lint to the CI efforts.

**Comment by TanyaCouture** [comment]
Tests passed:
    Vagrant
    AWS

Failed:
    DigitalOcean(passwords listed in error message so not pasted here)

**Comment by loshkovskyi** [comment]
@TanyaCouture, I have successfully deployed this branch on DigitalOcean and OpenStack (CIS). You can edit out the sensitive information from the output and paste it here or send with an email.

**Comment by sehqlr** [comment]
@loshkovskyi @TanyaCouture I was able to get DO to work, and it passed the test.

**Comment by ryane** [comment]
:thumbsup: #946 tracks the addition of ansible lint to the ci build

**Pull request merged**
