### PR TITLE
Update 'Checking Your Deployment' section of Getting Started

### LINKED ISSUE #1100: Better instructions in the 'Checking Your Deployment' section of the docs
It'd be helpful if we included more instructions in the Checking Your Deployment section of the docs. Right now it just says to check the ports for individual services, but we could provide more info, like how to use the terraform.py tool to get the `hostfile`, how to use Mantl UI for health checks, and so on.

### PR DESCRIPTION
**Pull request by sehqlr**
The documentation for checking mantl deployments is out of date. This section should introduce Mantl UI. Additionally, I added a section for using terraform.py as a stand-alone script. The copy needs to be looked at, and the screenshot added, so I need some feedback on that.

Fixes #1100

### CODE REVIEW

**Comment by sehqlr** [comment]
This could also fix #865

**Comment by ryane** [comment]
looks like a good start to me. I don't know if we need to include the sample output of terraform.py with those ip addresses. Maybe just say that it will ouput a list of ips and hostnames that can be included in a hosts file. Also, there is a mantlui screenshot [here](https://github.com/CiscoCloud/nginx-mantlui/) if you don't want to create a new one.

**Comment by sehqlr** [comment]
I added in the screenshot, linking our docs to the mantlui GH page. Also, I removed the IPs from the code block. I feel like having the output example there will help people see what it's supposed to look like, but is that a strong enough reason?

**Comment by ryane** [comment]
I don't have a strong opinion about it; if you think it is helpful, we can add it back. I just thought it looked a little confusing to see a long list of "real" ips. Maybe we can use x.x.x.x or would that be more confusing? Should we add a note that about certificate warnings in browsers for clusters with SSL turned on? And a note about authentication (indicate that it uses the credentials specified when you ran security-setup and how to find it in security.yml)?

**Comment by sehqlr** [comment]
Added in section about auth issues, and added in hostfile contents with x's. How is the copy in that paragraph I added?

**Comment by ryane** [comment]
lgtm, thanks!

**Pull request merged**
