### PR TITLE
Cumulative PR for monitoring/collectd

### PR DESCRIPTION
**Pull request by corebug**
This is a cumulative PR that incorporates (refactored):

* collectd base: https://github.com/CiscoCloud/microservices-infrastructure/pull/335
* Docker: https://github.com/CiscoCloud/microservices-infrastructure/pull/352
* Mesos: https://github.com/CiscoCloud/microservices-infrastructure/pull/347
* Marathon: https://github.com/CiscoCloud/microservices-infrastructure/pull/345
* ZooKeeper: https://github.com/CiscoCloud/microservices-infrastructure/pull/346

### CODE REVIEW

**Comment by stevendborrelli** [comment]
This looks great. Is this something we should merge into master?

**Comment by corebug** [comment]
@stevendborrelli 

There already are 5 PRs to master to be merged.
They do exactly the same things.
Please merge them.

Currently we have: 
* collectd base: https://github.com/CiscoCloud/microservices-infrastructure/pull/335
* Docker: https://github.com/CiscoCloud/microservices-infrastructure/pull/352
* Mesos: https://github.com/CiscoCloud/microservices-infrastructure/pull/347
* Marathon: https://github.com/CiscoCloud/microservices-infrastructure/pull/345
* ZooKeeper: https://github.com/CiscoCloud/microservices-infrastructure/pull/346

**Comment by corebug** [comment]
I think i'll redo those since they're outdated a bit, but i'll do it right after tests are finished.

**Comment by stevendborrelli** [comment]
@corebug thanks! Let me know and I'll start the merge process into master.

**Pull request merged**
