### PR TITLE
mantl-api: version 0.1.4

### PR DESCRIPTION
**Pull request by ryane**
supports frameworks that read mesos credentials from a file

### CODE REVIEW

**Comment by siddharthist** [comment]
What tests should pass for this?

**Comment by ryane** [comment]
At minimum, mantl-api should be running and healthy in marathon. On top of that, you could test installing some packages like Kafka, Cassandra, or Elasticsearch (that one uses the mesos credentials file)

**Comment by sehqlr** [comment]
I tested this on DO. mantl-api was healthy, and I was able to install Cassandra and Kafka. Do I need to test other providers?

**Comment by ryane** [comment]
I've tested it on my own cluster but if you want to double check you should install elasticsearch. That will confirm that the new location of the credentials file is working. It reads mesos credentials from /etc/sysconfig/mantl-api.

**Comment by TanyaCouture** [comment]
Tested on OS:
In Marathon: mantl-api running and healthy, kafka installed and healthy, cassandra installed and healthy

**Comment by tymofii-polekhin** [comment]
@ryane mantl-api fails to start on my dev cluster
```
time="2016-02-16T16:20:29Z" level=info msg="Starting mantl-api v0.1.4" 
time="2016-02-16T16:20:29Z" level=debug msg="Using Consul at consul.service.consul:8500 over http" 
time="2016-02-16T16:20:29Z" level=debug msg="Looking up consul domain" 
time="2016-02-16T16:20:29Z" level=debug msg="Discovered mesos service url: http://leader.mesos.service.consul:15050" 
time="2016-02-16T16:20:29Z" level=fatal msg="Secret file /etc/sysconfig/mantl-api does not exist" 
```
my cluster do not use `do_mesos_framework_auth` so /etc/sysconfig/mantl-api does not exists
```
- name: delete mantl-api credential
  when: not do_mesos_framework_auth|bool
  sudo: yes
  file:
    dest: /etc/sysconfig/mantl-api
    state: absent
  tags:
    - mesos
```

**Comment by ryane** [comment]
@tymofii-polekhin sorry about that. this should be fixed in #1145. If you want to fix an existing cluster, you will want to delete the `/etc/sysconfig/mantl-api` directory from all worker nodes if it exists (this was erroneously being created by the unneeded docker volume mount) and then bump the mantl-api version to 0.1.5 and restart it.

**Pull request merged**
