### PR TITLE
Feature/terraform openstack

### PR DESCRIPTION
**Pull request by ChrisAubuchon**
Add basic OpenStack functionality

### CODE REVIEW

**Comment by kenjones-cisco** [comment]
On the inventory plugin for terraform there are a couple of items.

Currently the args parser is defined globally, and there are other places in the code where there are local variables that are referencing a variable named "parser". By moving the definition of the args parser into main, that is completed avoided and there would be no confusion by about which variable is intended.

On the definition of the args parser,
`modes = parser.add_mutually_exclusive_group()`
If you include the following:
`modes = parser.add_mutually_exclusive_group(required=True)`

Then the following block of code is not required at all (argparser) will take care of it for you:
```
    if not args.list and not args.host:
        print('error: one of --list or --host is required', file=sys.stderr)
        print('{}')
        return 1
``` 

Was this tested when using this inventory plugin as part of executing an ansible playbook? The reason I ask, when I included the line:
```
from __future__ import print_function
```

In another plugin I created, it resulted in ansible generating errors during the playbook execution because ansible has been adamant about be python2 compatible such that much of their code you will see `print` called as built-in vs. function call.

**Comment by BrianHicks** [comment]
@kenjones-cisco good point about the groups, I didn't know about the required param. I won't be able to get to it today but it should be pretty simple if you'd like to submit a PR.

The print function works as part of the Ansible run. We did test it, of course. If you'd like to give it a shot and let me know of any errors, we can try to improve compatibility on various systems.

**Comment by kenjones-cisco** [comment]
@BrianHicks PR submitted.

As to the print comment, it could be the difference between library module and plugin module. Too bad ansible doesn't support py2 and py3 such that even thinking about this would be simpler.

**Comment by stevendborrelli** [comment]
@ChrisAubuchon @kenjones-cisco  do we feel this is this ready to merge?

**Comment by kenjones-cisco** [comment]
The feedback I provided has already been merged into the branch feature/terraform.

**Pull request merged**
