### PR TITLE
Removing ansible roles that are superseded by consul-rpm (PR#1)

### LINKED ISSUE #814: master fail | sysctl max file limit
Cloned master today and tried to deploy.
Got:
```
TASK: [common | sysctl max file limit] ****************************************
failed: [mi-worker-002] => {"failed": true, "parsed": false}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
BECOME-SUCCESS-wfzyckbrbwbuzllibrtsmdrwhpvsuzja
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
Traceback (most recent call last):
  File "/home/centos/.ansible/tmp/ansible-tmp-1447668228.64-62933258846373/sysctl", line 1936, in <module>
    main()
  File "/home/centos/.ansible/tmp/ansible-tmp-1447668228.64-62933258846373/sysctl", line 335, in main
    result = SysctlModule(module)
  File "/home/centos/.ansible/tmp/ansible-tmp-1447668228.64-62933258846373/sysctl", line 118, in __init__
    self.process()
  File "/home/centos/.ansible/tmp/ansible-tmp-1447668228.64-62933258846373/sysctl", line 157, in process
    elif not self._values_is_equal(self.proc_value, self.args['value']):
  File "/home/centos/.ansible/tmp/ansible-tmp-1447668228.64-62933258846373/sysctl", line 178, in _values_is_equal
    b = b.split()
AttributeError: 'int' object has no attribute 'split'
```

### PR DESCRIPTION
**Pull request by sehqlr**
This removes ansible roles that are superseded by my PR in ciscocloud/consul-rpm#1. This code was broken on older versions of ansible, so that will also fix #814

### CODE REVIEW

**Comment by ryane** [comment]
don't we need to add the new consul-rpm release (0.5.2-3) to the build? it looks like we are still using 0.5.2-2:

```
$ sudo yum list installed | grep -i consul
consul.x86_64                    0.5.2-2.el7.centos                    @/consul-0.5.2-2.el7.centos.x86_64
consul-template.x86_64           0.8.0-2.el7.centos                    @/consul-template-0.8.0-2.el7.centos.x86_64
consul-ui.x86_64                 0.5.2-2.el7.centos                    @/consul-ui-0.5.2-2.el7.centos.x86_64
consul-utils.x86_64              0.1.0-1.el7.centos                    @/consul-utils-0.1.0-1.el7.centos.x86_64
```

**Comment by sehqlr** [comment]
Thanks, @ryane.

**Comment by ryane** [comment]
```
TASK: [consul | install consul] ***********************************************
failed: [default] => {"changed": false, "failed": true, "rc": 1}
msg: Package at https://bintray.com/artifact/download/ciscocloud/rpm/consul-0.5.2-3.el7.centos.x86_64.rpm could not be installed
```

**Comment by ryane** [comment]
worked for me now that the package is in place

**Pull request merged**
