### PR TITLE
Enable NFS-mounted FS. Exclude loopback interfaces.

### PR DESCRIPTION
**Pull request by rodionos**

### CODE REVIEW

**Comment by rodionos** [comment]
"Failed verification of mi-control-01" not relevant to my pull request

**Comment by siddharthist** [comment]
@rodionos Would you mind providing a little explanation of what exactly this is supposed to do?

**Comment by rodionos** [comment]
These changes to colllectd interface plugin disable collection for local interface (there is no use) and enable all others. I'm not sure why veth (naming convention for interface names) by docker were disabled in the first place.

**Comment by stevendborrelli** [comment]
We're going to close this, as we are currently not supporting NFS (and are thinking of moving off collectd).

**Pull request closed without merging**
